import { StyleSheet, Platform, Dimensions } from "react-native";
import { SW, SH, NAVBAR_H, BOTTOM_INSET, COMPOSER_ABOVE_NAV, COLLAGE_W, COLLAGE_GAP } from "./dimensions";
import { STREAM_CARD_GAP, STREAM_CARD_W, WAVE_HEIGHTS, CARD_AVATAR_SIZE, CARD_AVATAR_OVERLAP, CARD_BANNER_H, MSG_HEADER_H, TOGGLE_W, TOGGLE_H, THUMB_SIZE, THUMB_TRAVEL, PROFILE_BANNER_H, PROFILE_AVATAR_SIZE, PROFILE_AVATAR_OVERLAP, SWATCH_SIZE } from "../../constants/feedLayout";

// Component-scoped StyleSheets extracted from app/feed.tsx.

export const spCard = StyleSheet.create({
  card: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    alignSelf: "flex-start",       // don't stretch to fill parent
    backgroundColor: "#0F1A12",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(29,185,84,0.25)",
    padding: 12,
    maxWidth: SW * 0.72,
  },
  cardMe: { alignSelf: "flex-end" },
  art: { width: 54, height: 54, borderRadius: 10, overflow: "hidden" },
  artFallback: {
    width: 54,
    height: 54,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "rgba(29,185,84,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  info: { flex: 1, gap: 2 },
  spotifyRow: { flexDirection: "row", alignItems: "center", gap: 4, marginBottom: 4 },
  spotifyLabel: { fontSize: 10, fontWeight: "700", color: "#1DB954", letterSpacing: 0.5 },
  trackName: { fontSize: 13, fontWeight: "700", color: "#fff", letterSpacing: -0.2 },
  artistName: { fontSize: 11, color: "rgba(255,255,255,0.45)", marginBottom: 8 },
  btnRow: { flexDirection: "row", gap: 7 },
  openBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: "rgba(29,185,84,0.12)",
    borderWidth: 1,
    borderColor: "rgba(29,185,84,0.35)",
  },
  openBtnText: { fontSize: 11, fontWeight: "700", color: "#1DB954" },
  saveBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
  },
  savedBtn: {
    backgroundColor: "rgba(29,185,84,0.12)",
    borderColor: "rgba(29,185,84,0.3)",
  },
  saveBtnText: { fontSize: 11, fontWeight: "600", color: "rgba(255,255,255,0.45)" },
  savedBtnText: { color: "#1DB954" },
});

export const lbStyles = StyleSheet.create({
  backdrop:  { flex: 1, backgroundColor: "#000" },
  header:    {
    flexDirection: "row", alignItems: "center", justifyContent: "space-between",
    paddingHorizontal: 20, paddingTop: 54, paddingBottom: 10,
  },
  counter:   { fontSize: 15, color: "rgba(255,255,255,0.6)", fontWeight: "600" },
  closeBtn:  { width: 42, height: 42, alignItems: "center", justifyContent: "center" },
  page:      { width: SW, flex: 1, justifyContent: "center", alignItems: "center" },
  fullImage: { width: SW, height: SH * 0.78 },
  videoFull: { width: SW, height: SH * 0.62 },
});

export const ds = StyleSheet.create({
  scrollContent: { paddingBottom: NAVBAR_H + BOTTOM_INSET + 40 },

  header: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", paddingHorizontal: 16, paddingTop: 8, paddingBottom: 16 },
  headerTitle: { fontSize: 48, fontWeight: "900", color: "#ffffff", letterSpacing: -1, lineHeight: 44 },
  iconBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: "rgba(255,255,255,0.08)", borderWidth: 1, borderColor: "rgba(255,255,255,0.12)", alignItems: "center", justifyContent: "center", marginBottom: 4 },

  searchWrap: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(255,255,255,0.07)", borderRadius: 16, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", marginHorizontal: 16, paddingHorizontal: 14, paddingVertical: 11, marginBottom: 16 },
  searchInput: { flex: 1, fontSize: 14, color: "#fff" },

  filtersRow: { paddingHorizontal: 16, gap: 8 },
  filterPill: { paddingHorizontal: 18, paddingVertical: 8, borderRadius: 20, backgroundColor: "rgba(255,255,255,0.07)", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)" },
  filterPillActive: { backgroundColor: "#AB00FF", borderColor: "#AB00FF" },
  filterPillText: { fontSize: 13, color: "rgba(255,255,255,0.5)", fontWeight: "600" },
  filterPillTextActive: { color: "#fff" },

  carouselCard: { borderRadius: 24, overflow: "hidden", height: 220 },
  featuredGradient: { flex: 1, padding: 20 },
  decoCircle: { position: "absolute", borderRadius: 999 },
  featuredBadge: { alignSelf: "flex-start", backgroundColor: "rgba(0,0,0,0.35)", borderRadius: 20, paddingHorizontal: 12, paddingVertical: 6, borderWidth: 1, borderColor: "rgba(255,255,255,0.15)" },
  featuredBadgeText: { fontSize: 12, color: "#CAFF00", fontWeight: "700" },
  featuredBottom: { gap: 6 },
  featuredTitle: { fontSize: 26, fontWeight: "900", color: "#fff", letterSpacing: -0.5 },
  featuredSub: { fontSize: 13, color: "rgba(255,255,255,0.65)" },
  featuredRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 4 },
  featuredTag: { backgroundColor: "rgba(255,255,255,0.15)", borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4 },
  featuredTagText: { fontSize: 11, color: "#fff", fontWeight: "600" },
  featuredCta: { backgroundColor: "#CAFF00", borderRadius: 20, paddingHorizontal: 16, paddingVertical: 8 },
  featuredCtaActive: { backgroundColor: "rgba(255,255,255,0.2)", borderWidth: 1, borderColor: "rgba(255,255,255,0.4)" },
  featuredCtaText: { fontSize: 13, color: "#0D0D0D", fontWeight: "800" },
  featuredCtaTextActive: { color: "#fff" },

  dotRow: { flexDirection: "row", justifyContent: "center", gap: 6, marginTop: 12 },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: "rgba(255,255,255,0.2)" },
  dotActive: { width: 18, backgroundColor: "#AB00FF" },

  sectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16, marginBottom: 14 },
  sectionTitle: { fontSize: 20, fontWeight: "800", color: "#fff", letterSpacing: -0.3 },
  sectionSub: { fontSize: 12, color: "rgba(255,255,255,0.35)", fontWeight: "500" },
  seeAll: { fontSize: 13, color: "#AB00FF", fontWeight: "600" },

  storiesRow: { paddingHorizontal: 16, gap: 20 },
  storyItem2: { alignItems: "center", width: 72 },
  storyRing2: { width: 68, height: 68, borderRadius: 34, borderWidth: 3, alignItems: "center", justifyContent: "center", marginBottom: 6 },
  storyAvatar2: { width: 60, height: 60, borderRadius: 30 },
  storyName2: { fontSize: 11, color: "rgba(255,255,255,0.5)", textAlign: "center" },

  artistsRow: { paddingHorizontal: 16, gap: 16 },
  artistCard: { alignItems: "center", width: 84 },
  artistAvatarRing: { width: 74, height: 74, borderRadius: 37, borderWidth: 3, alignItems: "center", justifyContent: "center", marginBottom: 8 },
  artistAvatar: { width: 66, height: 66, borderRadius: 33 },
  artistInitials: { fontSize: 22, fontWeight: "800" },
  artistName: { fontSize: 12, color: "#fff", fontWeight: "700", textAlign: "center", marginBottom: 2 },
  artistGenre: { fontSize: 10, color: "rgba(255,255,255,0.4)", textAlign: "center", marginBottom: 8 },
  followBtn: { paddingHorizontal: 12, paddingVertical: 5, borderRadius: 20, borderWidth: 1, borderColor: "rgba(255,255,255,0.25)" },
  followBtnText: { fontSize: 10, color: "rgba(255,255,255,0.6)", fontWeight: "700" },
  followBtnTextActive: { color: "#0D0D0D" },

  recsRow: { paddingHorizontal: 16, gap: 12 },
  recCard: { width: 158, backgroundColor: "rgba(255,255,255,0.06)", borderRadius: 18, overflow: "hidden", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },

  // Song card — vinyl aesthetic
  songThumb: { width: 158, height: 108, alignItems: "center", justifyContent: "center", overflow: "hidden" },
  vinylRing: { position: "absolute", borderRadius: 999, borderWidth: 1 },
  vinylCenter: { width: 42, height: 42, borderRadius: 21, borderWidth: 2, alignItems: "center", justifyContent: "center", overflow: "hidden" },
  vinylPhoto: { width: 42, height: 42, borderRadius: 21, resizeMode: "cover" },
  songDurationBadge: { position: "absolute", bottom: 8, right: 8, flexDirection: "row", alignItems: "center", gap: 3, backgroundColor: "rgba(0,0,0,0.45)", borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2 },
  songDurationText: { fontSize: 10, color: "rgba(255,255,255,0.6)", fontWeight: "600" },

  // Video card — thumbnail + play
  recThumb: { width: 158, height: 108, position: "relative" },
  recThumbImg: { width: "100%", height: "100%", resizeMode: "cover" },
  recPlayBtn: { position: "absolute", top: "50%", left: "50%", marginTop: -20, marginLeft: -20, width: 40, height: 40, borderRadius: 20, backgroundColor: "rgba(0,0,0,0.6)", alignItems: "center", justifyContent: "center", borderWidth: 1.5, borderColor: "rgba(255,255,255,0.35)" },
  videoBadge: { position: "absolute", top: 8, right: 8, borderRadius: 5, paddingHorizontal: 6, paddingVertical: 3 },
  videoBadgeText: { fontSize: 8, fontWeight: "900", letterSpacing: 0.5 },
  recDurationBadge: { position: "absolute", bottom: 8, left: 8, backgroundColor: "rgba(0,0,0,0.6)", borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2 },
  recDurationText: { fontSize: 10, color: "#fff", fontWeight: "600" },

  recInfo: { padding: 10, gap: 2 },
  recTitle: { fontSize: 13, color: "#fff", fontWeight: "700" },
  recArtist: { fontSize: 11, color: "rgba(255,255,255,0.45)" },
  recBottom: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 6 },
  recGenre: { fontSize: 10, fontWeight: "700" },

  meetsCol: { paddingHorizontal: 16, gap: 12 },
  meetCard: { backgroundColor: "rgba(255,255,255,0.06)", borderRadius: 20, flexDirection: "row", overflow: "hidden", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  meetStrip: { width: 4 },
  meetBody: { flex: 1, padding: 14, gap: 8 },
  meetTopRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  meetTitle: { fontSize: 15, fontWeight: "800", color: "#fff", marginBottom: 2 },
  meetSubtitle: { fontSize: 12, color: "rgba(255,255,255,0.45)", lineHeight: 16 },
  meetDateBadge: { borderRadius: 10, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1, alignItems: "center", minWidth: 58 },
  meetDateText: { fontSize: 10, fontWeight: "800", textAlign: "center", lineHeight: 14 },
  meetMeta: { flexDirection: "row", alignItems: "center", gap: 4 },
  meetLocation: { fontSize: 12, color: "rgba(255,255,255,0.4)" },
  meetBottomRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  meetTag: { backgroundColor: "rgba(255,255,255,0.08)", borderRadius: 10, paddingHorizontal: 9, paddingVertical: 4 },
  meetTagText: { fontSize: 11, color: "rgba(255,255,255,0.5)", fontWeight: "600" },
  rsvpBtn: { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, borderWidth: 1 },
  rsvpText: { fontSize: 11, fontWeight: "800" },

  emptyState: { alignItems: "center", paddingTop: 60, gap: 12 },
  emptyText: { fontSize: 15, color: "rgba(255,255,255,0.3)", fontWeight: "500" },
});

export const lmStyles = StyleSheet.create({
  card: { borderRadius: 16, overflow: "hidden", backgroundColor: "#111", marginBottom: STREAM_CARD_GAP, minHeight: 196, justifyContent: "space-between" },
  cardTop: { flexDirection: "row", justifyContent: "space-between", padding: 8 },
  liveBadge: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: "#E8000F", borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3 },
  liveDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: "#fff" },
  liveBadgeText: { fontSize: 10, color: "#fff", fontWeight: "800" },
  viewerBadge: { flexDirection: "row", alignItems: "center", gap: 3, backgroundColor: "rgba(0,0,0,0.55)", borderRadius: 6, paddingHorizontal: 6, paddingVertical: 3 },
  viewerText: { fontSize: 10, color: "#fff", fontWeight: "700" },
  cardBottom: { padding: 10, gap: 3 },
  cardTitle: { fontSize: 14, color: "#fff", fontWeight: "800", lineHeight: 18 },
  cardTrack: { fontSize: 11, color: "rgba(255,255,255,0.7)" },
  cardHost: { fontSize: 11, color: "rgba(255,255,255,0.5)", marginBottom: 6 },
  joinBtn: { backgroundColor: "#AB00FF", borderRadius: 18, paddingVertical: 8, alignItems: "center" },
  joinBtnText: { fontSize: 13, fontWeight: "800", color: "#fff" },
});

export const ms = StyleSheet.create({
  scrollContent: { paddingBottom: NAVBAR_H + BOTTOM_INSET + 40 },
  header: { paddingHorizontal: 16, paddingTop: 8, paddingBottom: 16 },
  headerTitle: { fontSize: 48, fontWeight: "900", color: "#fff", letterSpacing: -1, lineHeight: 44 },

  tabRow: { flexDirection: "row", paddingHorizontal: 16, gap: 8, marginBottom: 20 },
  tabPill: { flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, backgroundColor: "rgba(255,255,255,0.07)", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)" },
  tabPillActive: { backgroundColor: "#AB00FF", borderColor: "#AB00FF" },
  tabText: { fontSize: 13, color: "rgba(255,255,255,0.5)", fontWeight: "600" },
  tabTextActive: { color: "#fff" },
  liveTabDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: "rgba(255,80,80,0.45)" },
  liveTabDotActive: { backgroundColor: "#FF3333" },

  grid: { flexDirection: "row", paddingHorizontal: 16, gap: STREAM_CARD_GAP },
  col: { flex: 1, gap: STREAM_CARD_GAP },

  card: { width: STREAM_CARD_W, borderRadius: 16, overflow: "hidden", backgroundColor: "#111", justifyContent: "space-between" },

  cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", padding: 8 },
  liveBadge: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: "#E8000F", borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3 },
  liveDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: "#fff" },
  liveBadgeText: { fontSize: 10, color: "#fff", fontWeight: "800" },
  meetBadge: { backgroundColor: "#AB00FF", borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3 },
  meetBadgeText: { fontSize: 10, color: "#fff", fontWeight: "800" },
  viewerBadge: { flexDirection: "row", alignItems: "center", gap: 3, backgroundColor: "rgba(0,0,0,0.55)", borderRadius: 6, paddingHorizontal: 6, paddingVertical: 3 },
  viewerText: { fontSize: 10, color: "#fff", fontWeight: "700" },

  waveWrap: { position: "absolute", bottom: 44, left: 0, right: 0, flexDirection: "row", alignItems: "flex-end", justifyContent: "center", gap: 3, paddingHorizontal: 10 },
  waveBar: { width: 4, borderRadius: 2, opacity: 0.75 },

  cardBottom: { padding: 9, gap: 2 },
  typeTag: { alignSelf: "flex-start", width: 18, height: 18, borderRadius: 9, alignItems: "center", justifyContent: "center", marginBottom: 3 },
  cardTitle: { fontSize: 12, color: "#fff", fontWeight: "700", lineHeight: 16 },
  cardHost: { fontSize: 10, color: "rgba(255,255,255,0.45)", marginTop: 1 },
});

export const pplStyles = StyleSheet.create({
  card: {
    backgroundColor: "#111113",
    borderRadius: 18,
    overflow: "hidden",
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
  },
  bannerWrap: { height: CARD_BANNER_H, overflow: "hidden" },
  bannerFollowWrap: { position: "absolute", bottom: 10, right: 10 },
  avatarRow: {
    paddingHorizontal: 14,
    marginTop: -CARD_AVATAR_OVERLAP,
    flexDirection: "row",
    alignItems: "flex-end",
  },
  avatarImg: {
    width: CARD_AVATAR_SIZE, height: CARD_AVATAR_SIZE,
    borderRadius: 14,
    borderWidth: 2.5, borderColor: "#111113",
    backgroundColor: "#1A1A1C",
  },
  avatarFallback: {
    width: CARD_AVATAR_SIZE, height: CARD_AVATAR_SIZE,
    borderRadius: 14,
    borderWidth: 2.5, borderColor: "#111113",
    backgroundColor: "#AB00FF33",
    alignItems: "center" as const, justifyContent: "center" as const,
  },
  avatarInitials: { fontSize: 18, fontWeight: "800" as const, color: "#AB00FF" },
  info: { paddingHorizontal: 14, paddingBottom: 14, paddingTop: 8 },
  nameRow: { flexDirection: "row" as const, alignItems: "center" as const, gap: 6, flexShrink: 1 },
  name: { fontSize: 15, fontWeight: "700" as const, color: "#fff", flexShrink: 1 },
  verifiedBadge: {
    backgroundColor: "#FF6C1A", borderRadius: 8,
    paddingHorizontal: 5, paddingVertical: 1,
  },
  verifiedText: { fontSize: 10, fontWeight: "800" as const, color: "#fff" },
  username: { fontSize: 12, color: "rgba(255,255,255,0.38)", marginTop: 2 },
  bio: { fontSize: 13, color: "rgba(255,255,255,0.52)", marginTop: 6, lineHeight: 18 },
  statsRow: { flexDirection: "row" as const, alignItems: "center" as const, marginTop: 10 },
  statNum: { fontSize: 13, fontWeight: "700" as const, color: "#fff" },
  statLabel: { fontSize: 12, color: "rgba(255,255,255,0.38)" },
  pinnedRow: {
    flexDirection: "row" as const, alignItems: "center" as const, gap: 7,
    marginTop: 10,
    backgroundColor: "rgba(255,108,26,0.08)",
    borderRadius: 10, paddingHorizontal: 10, paddingVertical: 7,
  },
  pinnedArt: { width: 26, height: 26, borderRadius: 5 },
  pinnedArtFallback: {
    width: 26, height: 26, borderRadius: 5,
    backgroundColor: "rgba(255,255,255,0.07)",
    alignItems: "center" as const, justifyContent: "center" as const,
  },
  pinnedText: { flex: 1, fontSize: 12, color: "rgba(255,255,255,0.6)", fontWeight: "500" as const },
  genreRow: { flexDirection: "row" as const, flexWrap: "wrap" as const, gap: 6, marginTop: 10 },
  genreChip: {
    backgroundColor: "rgba(171,0,255,0.12)",
    borderRadius: 10, paddingHorizontal: 9, paddingVertical: 4,
    borderWidth: 1, borderColor: "rgba(171,0,255,0.2)",
  },
  genreText: { fontSize: 11, fontWeight: "600" as const, color: "#AB00FF" },
  followBtn: {
    paddingHorizontal: 14, paddingVertical: 7, borderRadius: 20,
    backgroundColor: "#fff",
  },
  followingBtn: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
  },
  followBtnText: { fontSize: 13, fontWeight: "700" as const, color: "#111" },
  followingBtnText: { color: "#fff" },

  // ── Artist card (standalone artists table) ────────────────────────────────
  artistCard: {
    backgroundColor: "#111113",
    borderRadius: 18,
    overflow: "hidden",
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
  },
  artistBanner: { height: CARD_BANNER_H, overflow: "hidden" },
  artistAvatarRow: {
    paddingHorizontal: 14,
    marginTop: -CARD_AVATAR_OVERLAP,
    flexDirection: "row" as const,
    alignItems: "flex-end" as const,
  },
  artistAvatar: {
    width: CARD_AVATAR_SIZE, height: CARD_AVATAR_SIZE,
    borderRadius: 14,
    borderWidth: 2.5, borderColor: "#111113",
    backgroundColor: "#1A1A1C",
  },
  artistAvatarFallback: {
    alignItems: "center" as const, justifyContent: "center" as const,
    backgroundColor: "rgba(255,108,26,0.18)",
  },
  artistInfo: { paddingHorizontal: 14, paddingBottom: 14, paddingTop: 8 },
  artistBadge: {
    paddingHorizontal: 7, paddingVertical: 2, borderRadius: 8,
    backgroundColor: "rgba(171,0,255,0.2)",
    borderWidth: 1, borderColor: "rgba(171,0,255,0.35)",
  },
  artistBadgeText: { fontSize: 10, fontWeight: "800" as const, color: "#AB00FF" },
});

export const msgStyles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
    height: MSG_HEADER_H,
  },
  dropdownTrigger: { flexDirection: "row", alignItems: "center", gap: 6 },
  headerTitle: { fontSize: 32, fontWeight: "900", color: "#fff", letterSpacing: -0.5 },

  dropdown: {
    position: "absolute",
    top: MSG_HEADER_H,
    left: 16,
    right: 16,
    backgroundColor: "#1C1C1E",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
  },
  dropdownRow: { flexDirection: "row", alignItems: "center", paddingHorizontal: 18, paddingVertical: 15 },
  dropdownRowBorder: { borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.06)" },
  dropdownRowActive: { backgroundColor: "rgba(171,0,255,0.1)" },
  dropdownRowText: { fontSize: 16, fontWeight: "600", color: "rgba(255,255,255,0.4)" },
  dropdownRowTextActive: { color: "#fff" },
  dropdownBadge: { backgroundColor: "#E8000F", borderRadius: 10, minWidth: 22, height: 22, alignItems: "center", justifyContent: "center", paddingHorizontal: 7 },
  dropdownBadgeActive: { backgroundColor: "#AB00FF" },
  dropdownBadgeText: { fontSize: 11, color: "#fff", fontWeight: "800" },

  // ── Direct messages ──
  dmRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 13,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.05)",
  },
  dmAvatarWrap: { position: "relative" },
  dmAvatar: { width: 52, height: 52, borderRadius: 26, alignItems: "center", justifyContent: "center" },
  dmAvatarText: { fontSize: 18, fontWeight: "800", color: "#AB00FF" },
  onlineDot: {
    position: "absolute",
    bottom: 1, right: 1,
    width: 12, height: 12, borderRadius: 6,
    backgroundColor: "#00E5A0",
    borderWidth: 2, borderColor: "#0D0D0D",
  },
  dmContent: { flex: 1 },
  dmTopRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 4 },
  dmName: { fontSize: 15, fontWeight: "600", color: "rgba(255,255,255,0.5)", paddingTop: 8 },
  dmNameUnread: { color: "#fff", fontWeight: "800" },
  dmTime: { fontSize: 12, color: "rgba(255,255,255,0.28)" },
  dmBottomRow: { flexDirection: "row", alignItems: "center" },
  dmPreview: { fontSize: 13, color: "rgba(255,255,255,0.28)", flex: 1 },
  dmPreviewUnread: { color: "rgba(255,255,255,0.55)" },
  dmUnreadBadge: {
    backgroundColor: "#AB00FF",
    borderRadius: 10, minWidth: 20, height: 20,
    alignItems: "center", justifyContent: "center",
    paddingHorizontal: 6, marginLeft: 10,
  },
  dmUnreadBadgeText: { fontSize: 11, color: "#fff", fontWeight: "800" },

  // ── Group chats ──
  gcRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 13,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.05)",
  },
  gcAvatarStack: { width: 52, height: 52, position: "relative" },
  gcAvatarBack: {
    position: "absolute",
    bottom: 0, right: 0,
    width: 30, height: 30, borderRadius: 15,
    borderWidth: 2, borderColor: "#0D0D0D",
    overflow: "hidden",
  },
  gcAvatarFront: {
    position: "absolute",
    top: 0, left: 0,
    width: 38, height: 38, borderRadius: 19,
    borderWidth: 2, borderColor: "#0D0D0D",
    overflow: "hidden",
  },
  gcContent: { flex: 1 },
  gcTopRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 3 },
  gcName: { fontSize: 15, fontWeight: "600", color: "rgba(255,255,255,0.5)", flex: 1, marginRight: 8 },
  gcNameUnread: { color: "#fff", fontWeight: "800" },
  gcTime: { fontSize: 12, color: "rgba(255,255,255,0.28)" },
  gcBottomRow: { flexDirection: "row", alignItems: "flex-start" },
  gcPreview: { fontSize: 13, color: "rgba(255,255,255,0.28)" },
  gcPreviewUnread: { color: "rgba(255,255,255,0.55)" },
  gcSender: { fontWeight: "700", color: "rgba(255,255,255,0.45)" },
  gcMemberCount: { fontSize: 11, color: "rgba(255,255,255,0.22)", marginTop: 2 },
  gcUnreadBadge: {
    backgroundColor: "#FF6B35",
    borderRadius: 10, minWidth: 20, height: 20,
    alignItems: "center", justifyContent: "center",
    paddingHorizontal: 6, marginLeft: 10, marginTop: 1,
  },
  gcUnreadBadgeText: { fontSize: 11, color: "#fff", fontWeight: "800" },

  // ── Community ──
  communityCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
    padding: 16,
    gap: 12,
  },
  communityTopRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  communityLeftMeta: { flexDirection: "row", alignItems: "center", flex: 1 },
  activeDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#00E5A0" },
  activeText: { fontSize: 12, color: "#00E5A0", fontWeight: "700", marginLeft: 5 },
  viewerStack: { flexDirection: "row" },
  viewerAvatarWrap: {
    marginLeft: -5,
    borderRadius: 9,
    borderWidth: 1.5, borderColor: "#0D0D0D",
    overflow: "hidden",
    width: 18, height: 18,
  },
  followerCount: { fontSize: 12, color: "rgba(255,255,255,0.35)", marginLeft: 8 },
  followCommunityBtn: {
    flexDirection: "row", alignItems: "center",
    backgroundColor: "#AB00FF",
    borderRadius: 20, paddingHorizontal: 14, paddingVertical: 7,
  },
  followCommunityBtnActive: { backgroundColor: "rgba(171,0,255,0.15)", borderWidth: 1, borderColor: "#AB00FF" },
  followCommunityText: { fontSize: 13, color: "#fff", fontWeight: "700" },
  communityTitle: { fontSize: 20, fontWeight: "900", color: "#fff", letterSpacing: -0.3, lineHeight: 26 },
  communityTagsRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  communityTag: { backgroundColor: "rgba(202,255,0,0.08)", borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4 },
  communityTagText: { fontSize: 12, color: "#CAFF00", fontWeight: "700" },
  communityDivider: { height: 1, backgroundColor: "rgba(255,255,255,0.06)" },
  authorRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  authorName: { fontSize: 13, color: "rgba(255,255,255,0.5)", fontWeight: "700" },
  authorFollowers: { fontSize: 11, color: "rgba(255,255,255,0.25)" },
  authorDate: { fontSize: 12, color: "rgba(255,255,255,0.25)" },

  // ── Now Playing stories strip ──
  nowPlayingSection: {
    paddingTop: 4,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  nowPlayingLabel: {
    fontSize: 11,
    color: "rgba(255,255,255,0.35)",
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  nowPlayingRow: { paddingHorizontal: 16, gap: 20 },
});

export const chatStyles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 6,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.07)",
  },
  backBtn: { width: 34, height: 34, alignItems: "center", justifyContent: "center" },
  headerCenter: { flex: 1, flexDirection: "row", alignItems: "center", gap: 8, minWidth: 0 },
  headerOnlineDot: {
    position: "absolute", bottom: 0, right: 0,
    width: 10, height: 10, borderRadius: 5,
    backgroundColor: "#00E5A0",
    borderWidth: 2, borderColor: "#0D0D0D",
  },
  headerName: { fontSize: 15, fontWeight: "800", color: "#fff" },
  headerStatus: { fontSize: 11, color: "#00E5A0", fontWeight: "600" },

  // Start Jam pill
  jamBtn: {
    flexDirection: "row", alignItems: "center", gap: 4,
    backgroundColor: "#CAFF00", borderRadius: 20,
    paddingHorizontal: 11, paddingVertical: 6,
  },
  jamBtnText: { fontSize: 12, color: "#0D0D0D", fontWeight: "800" },

  // Call / video icon buttons
  headerIconBtn: {
    width: 34, height: 34, borderRadius: 17,
    backgroundColor: "rgba(255,255,255,0.07)",
    alignItems: "center", justifyContent: "center",
    borderWidth: 1, borderColor: "rgba(255,255,255,0.09)",
  },

  // Messages list
  messagesContent: { paddingHorizontal: 14, paddingTop: 8, paddingBottom: 16 },
  msgWrap: { alignSelf: "flex-start", maxWidth: SW * 0.74, gap: 14 },
  msgWrapMe: { alignSelf: "flex-end" },
  bubble: { paddingHorizontal: 14, paddingTop: 9, paddingBottom: 7, borderRadius: 18 },
  bubbleThem: { backgroundColor: "#1C1C1E" },
  bubbleMe:   { backgroundColor: "#AB00FF" },
  bubbleText: { fontSize: 16, color: "rgba(255,255,255,0.82)", lineHeight: 21, fontWeight: "700" },
  bubbleTextMe: { color: "#fff" },
  bubbleTime: { fontSize: 10, color: "rgba(255,255,255,0.3)", textAlign: "right", marginTop: 3 },
  bubbleTimeMe: { color: "rgba(255,255,255,0.55)" },

  // Input bar — no longer absolute, sits in document flow
  inputBar: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: BOTTOM_INSET,
    backgroundColor: "#0D0D0D",
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.07)",
  },
  inputPlusBtn: { paddingBottom: 7 },
  inputWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-end",
    backgroundColor: "rgba(255,255,255,0.07)",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    gap: 8,
  },
  input: { flex: 1, fontSize: 15, color: "#fff", maxHeight: 100, paddingVertical: 7 },
  inputAction: { width: 30, height: 30, alignItems: "center", justifyContent: "center" },
  sendBtn: { backgroundColor: "#AB00FF", borderRadius: 15 },

  // Reply quote shown inside received/sent bubbles
  replyQuote: {
    flexDirection: "row",
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 10,
    marginBottom: 4,
    overflow: "hidden",
    maxWidth: SW * 0.65,
  },
  replyQuoteMe: { alignSelf: "flex-end" },
  replyQuoteAccent: { width: 3, backgroundColor: "rgba(255,255,255,0.35)" },
  replyQuoteText: {
    fontSize: 12,
    color: "rgba(255,255,255,0.45)",
    paddingHorizontal: 8,
    paddingVertical: 5,
    flex: 1,
  },

  // Reply-to strip above input bar
  replyBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
  },
  replyBarAccent: { width: 3, height: 32, borderRadius: 2, backgroundColor: "#AB00FF" },
  replyBarName: { fontSize: 11, fontWeight: "700", color: "#AB00FF", marginBottom: 2 },
  replyBarPreview: { fontSize: 12, color: "rgba(255,255,255,0.5)" },

  // Typing indicator
  typingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  typingBubble: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#1C1C1E",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(255,255,255,0.55)",
  },
  typingName: { fontSize: 11, color: "rgba(255,255,255,0.3)" },
});

export const pdStyles = StyleSheet.create({
  screen: { backgroundColor: "#0D0D0D" },
  hero: { minHeight: 340, justifyContent: "flex-end", overflow: "hidden" },
  backBtn: { position: "absolute", top: 0, left: 0, paddingHorizontal: 18, paddingBottom: 0, zIndex: 10 },
  backIcon: { fontSize: 32, color: "#fff", fontWeight: "300", lineHeight: 36 },
  artMosaic: { flexDirection: "row", flexWrap: "wrap", width: 130, height: 130, borderRadius: 16, overflow: "hidden", alignSelf: "center", marginBottom: 20 },
  mosaicCell: { width: 65, height: 65 },
  heroInfo: { paddingHorizontal: 20, paddingBottom: 24 },
  heroTitle: { fontSize: 28, fontWeight: "900", color: "#fff", lineHeight: 34, marginBottom: 10 },
  heroMetaRow: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 14, flexWrap: "wrap" },
  sourceIconBadge: { width: 18, height: 18, borderRadius: 4, alignItems: "center", justifyContent: "center" },
  sourceIconText: { fontSize: 10, fontWeight: "900", color: "#fff" },
  heroMetaText: { fontSize: 13, color: "rgba(255,255,255,0.55)", fontWeight: "500" },
  heroMetaDot: { fontSize: 13, color: "rgba(255,255,255,0.25)" },
  showOnProfileBtn: {
    alignSelf: "flex-start",
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  showOnProfileText: { fontSize: 13, color: "#fff", fontWeight: "600" },
  playBtn: { position: "absolute", bottom: 20, right: 20, width: 54, height: 54, borderRadius: 27, alignItems: "center", justifyContent: "center", shadowColor: "#000", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.4, shadowRadius: 8, elevation: 8 },
  playIcon: { fontSize: 20, color: "#fff", marginLeft: 3 },
  actionBar: { flexDirection: "row", alignItems: "center", paddingHorizontal: 8, paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.07)" },
  actionBtn: { flex: 1, alignItems: "center", justifyContent: "center", gap: 4 },
  actionIcon: { fontSize: 24, color: "rgba(255,255,255,0.7)" },
  actionCount: { fontSize: 11, color: "rgba(255,255,255,0.45)", fontWeight: "600" },
  songListDivider: { height: 8 },
  songRow: { flexDirection: "row", alignItems: "center", paddingHorizontal: 16, paddingVertical: 12, gap: 14 },
  songInfo: { flex: 1 },
  songTitle: { fontSize: 15, fontWeight: "600", color: "#fff", marginBottom: 3 },
  songArtist: { fontSize: 13, color: "rgba(255,255,255,0.4)" },
  songArt: { width: 46, height: 46, borderRadius: 8, alignItems: "center", justifyContent: "center", flexShrink: 0 },
  songDivider: { height: 1, backgroundColor: "rgba(255,255,255,0.05)", marginHorizontal: 16 },
});

export const cpStyles = StyleSheet.create({
  // Filter pills
  filterRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  filterBtn: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)', backgroundColor: 'rgba(255,255,255,0.04)' },
  filterBtnActive: { borderColor: '#FF6C1A', backgroundColor: 'rgba(255,108,26,0.12)' },
  filterLabel: { fontSize: 13, fontWeight: '600', color: 'rgba(255,255,255,0.38)' },
  filterLabelActive: { color: '#FF6C1A' },
  // Create playlist button
  createBtn: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 12, paddingHorizontal: 14, backgroundColor: 'rgba(255,108,26,0.07)', borderRadius: 14, borderWidth: 1, borderColor: 'rgba(255,108,26,0.18)', marginBottom: 6 },
  createBtnText: { fontSize: 14, fontWeight: '700', color: '#FF6C1A' },
  // Profile badge on card
  profileBadge: { paddingHorizontal: 7, paddingVertical: 3, borderRadius: 8, backgroundColor: 'rgba(171,0,255,0.15)', marginRight: 2 },
  profileBadgeText: { fontSize: 10, fontWeight: '700', color: '#AB00FF' },
  // Dialog overlay + sheet
  dialogOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.72)', justifyContent: 'flex-end' },
  dialogSheet: { backgroundColor: '#161618', borderTopLeftRadius: 28, borderTopRightRadius: 28, paddingHorizontal: 20, paddingTop: 12, borderTopWidth: 1, borderColor: 'rgba(255,255,255,0.08)', maxHeight: SH * 0.88 },
  dialogHandle: { width: 38, height: 4, borderRadius: 2, backgroundColor: 'rgba(255,255,255,0.15)', alignSelf: 'center', marginBottom: 20 },
  dialogTitle: { fontSize: 18, fontWeight: '800', color: '#fff', marginBottom: 18 },
  // Image picker
  imagePicker: { width: 90, height: 90, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: 1.5, borderColor: 'rgba(255,255,255,0.12)', borderStyle: 'dashed', alignItems: 'center', justifyContent: 'center', alignSelf: 'center', marginBottom: 20, overflow: 'hidden' },
  imagePickerText: { fontSize: 11, color: 'rgba(255,255,255,0.3)', marginTop: 4 },
  // Form fields
  label: { fontSize: 11, fontWeight: '700', color: 'rgba(255,255,255,0.35)', letterSpacing: 0.9, marginBottom: 8 },
  input: { backgroundColor: 'rgba(255,255,255,0.07)', borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, fontSize: 15, color: '#fff', marginBottom: 18, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  // Tags
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 10 },
  tagChip: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 20, backgroundColor: 'rgba(171,0,255,0.14)', borderWidth: 1, borderColor: 'rgba(171,0,255,0.28)' },
  tagChipText: { fontSize: 12, fontWeight: '600', color: '#AB00FF' },
  tagInputRow: { flexDirection: 'row', gap: 8, marginBottom: 20 },
  tagInput: { flex: 1, backgroundColor: 'rgba(255,255,255,0.07)', borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10, fontSize: 14, color: '#fff', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  addTagBtn: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.08)', justifyContent: 'center' },
  addTagBtnText: { fontSize: 14, fontWeight: '700', color: '#fff' },
  // Create submit
  createSubmitBtn: { backgroundColor: '#FF6C1A', borderRadius: 14, paddingVertical: 14, alignItems: 'center', marginTop: 4 },
  createSubmitText: { fontSize: 16, fontWeight: '800', color: '#fff' },
  // Mode tabs (Add Song dialog)
  modeRow: { flexDirection: 'row', gap: 8, marginBottom: 16 },
  modeBtn: { flex: 1, paddingVertical: 10, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.06)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', alignItems: 'center' },
  modeBtnActive: { backgroundColor: 'rgba(255,108,26,0.12)', borderColor: '#FF6C1A' },
  modeBtnText: { fontSize: 13, fontWeight: '700', color: 'rgba(255,255,255,0.4)' },
  modeBtnTextActive: { color: '#FF6C1A' },
  // Search
  searchRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  searchInput: { flex: 1, backgroundColor: 'rgba(255,255,255,0.07)', borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10, fontSize: 14, color: '#fff', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  searchBtn: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 12, backgroundColor: '#FF6C1A', alignItems: 'center', justifyContent: 'center' },
  // Track rows
  trackRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.05)' },
  trackArt: { width: 46, height: 46, borderRadius: 8, backgroundColor: '#1a0a2e', flexShrink: 0 },
  trackInfo: { flex: 1 },
  trackName: { fontSize: 14, fontWeight: '600', color: '#fff', marginBottom: 2 },
  trackArtist: { fontSize: 12, color: 'rgba(255,255,255,0.38)' },
  // Add buttons
  addBtn: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 10, backgroundColor: 'rgba(255,108,26,0.12)', borderWidth: 1, borderColor: 'rgba(255,108,26,0.25)' },
  addBtnText: { fontSize: 12, fontWeight: '700', color: '#FF6C1A' },
  addBtnDone: { backgroundColor: 'rgba(29,185,84,0.12)', borderColor: 'rgba(29,185,84,0.3)' },
  addBtnTextDone: { color: '#1DB954' },
  // Add Song button in detail hero
  addSongBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, alignSelf: 'flex-start', paddingHorizontal: 14, paddingVertical: 7, borderRadius: 20, backgroundColor: 'rgba(255,108,26,0.1)', borderWidth: 1, borderColor: 'rgba(255,108,26,0.28)', marginTop: 10 },
  addSongBtnText: { fontSize: 13, fontWeight: '700', color: '#FF6C1A' },
});

export const linksSheetStyles = StyleSheet.create({
  sheet: {
    position: "absolute", bottom: 0, left: 0, right: 0,
    backgroundColor: "#1A1A1C",
    borderTopLeftRadius: 24, borderTopRightRadius: 24,
    paddingBottom: BOTTOM_INSET + 16,
    borderTopWidth: 1, borderColor: "rgba(255,255,255,0.08)",
  },
  handle:  { width: 36, height: 4, borderRadius: 2, backgroundColor: "rgba(255,255,255,0.15)", alignSelf: "center", marginTop: 10, marginBottom: 4 },
  heading: { fontSize: 11, fontWeight: "700", letterSpacing: 1, color: "rgba(255,255,255,0.3)", textTransform: "uppercase", paddingHorizontal: 20, paddingTop: 8, paddingBottom: 10 },
  row:     { flexDirection: "row", alignItems: "center", paddingHorizontal: 20, paddingVertical: 13, gap: 12, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "rgba(255,255,255,0.07)" },
  iconWrap:    { width: 44, height: 44, borderRadius: 10, backgroundColor: "rgba(255,108,26,0.13)", alignItems: "center", justifyContent: "center" },
  spotifyWrap: { width: 44, height: 44, borderRadius: 10, backgroundColor: "rgba(29,185,84,0.12)", alignItems: "center", justifyContent: "center" },
  art:         { width: 44, height: 44, borderRadius: 8 },
  artCircle:   { width: 44, height: 44, borderRadius: 22 },
  domain: { fontSize: 14, fontWeight: "600", color: "#fff" },
  path:   { fontSize: 12, color: "rgba(255,255,255,0.35)", marginTop: 1 },
});

export const settingsOverlayStyles = StyleSheet.create({
  sheet: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#1a1a1f",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    paddingBottom: 40,
    overflow: "hidden",
  },
  handle: {
    alignSelf: "center",
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.18)",
    marginTop: 12,
    marginBottom: 20,
  },
  title: {
    fontSize: 17,
    fontWeight: "700",
    color: "#fff",
    paddingHorizontal: 20,
    marginBottom: 8,
  },
  logoutRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 14,
    marginHorizontal: 12,
    marginTop: 4,
    backgroundColor: "rgba(255,77,109,0.08)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,77,109,0.18)",
  },
  logoutIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(255,77,109,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  logoutLabel: { flex: 1, fontSize: 15, fontWeight: "600", color: "#ff4d6d" },
  confirmBlock: { paddingHorizontal: 20, paddingTop: 8, gap: 10 },
  confirmTitle: { fontSize: 19, fontWeight: "800", color: "#fff", letterSpacing: -0.3 },
  confirmSub: { fontSize: 13, color: "rgba(255,255,255,0.45)", lineHeight: 18, marginBottom: 4 },
  saveBtn: {
    backgroundColor: "#AB00FF",
    borderRadius: 16,
    paddingVertical: 15,
    alignItems: "center",
  },
  saveBtnText: { fontSize: 15, fontWeight: "700", color: "#fff" },
  skipBtn: {
    borderRadius: 16,
    paddingVertical: 13,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  skipBtnText: { fontSize: 15, fontWeight: "600", color: "rgba(255,255,255,0.55)" },

  // ── Generic menu row (used for Connected Apps, etc.) ──────────────────────
  menuRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 14,
    marginHorizontal: 12,
    marginTop: 4,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  menuIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  menuLabel: { flex: 1, fontSize: 15, fontWeight: "600", color: "#fff" },

  // ── Connected Apps sub-screen ─────────────────────────────────────────────
  subHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.07)",
    marginBottom: 8,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  subTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
  },

  // Spotify app row
  appRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginHorizontal: 16,
    marginVertical: 6,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  spotifyLogoWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "rgba(29,185,84,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  appName:   { fontSize: 15, fontWeight: "700", color: "#fff" },
  appStatus: { fontSize: 12, color: "rgba(255,255,255,0.4)", marginTop: 2 },

  // Right side of app row when connected
  connectedRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  connectedDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#1DB954",
  },
  disconnectBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },

  // Connect button (when disconnected)
  connectBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#1DB954",
  },
  connectBtnText: { fontSize: 13, fontWeight: "700", color: "#fff" },

  // Disconnect confirmation block
  disconnectConfirm: {
    marginHorizontal: 16,
    marginTop: 12,
    padding: 16,
    backgroundColor: "rgba(255,77,109,0.08)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,77,109,0.18)",
    gap: 10,
  },
  disconnectConfirmTitle: { fontSize: 15, fontWeight: "700", color: "#fff" },
  disconnectConfirmSub:   { fontSize: 13, color: "rgba(255,255,255,0.45)", lineHeight: 18 },
  disconnectBtnRow:       { flexDirection: "row", gap: 10, marginTop: 2 },
  disconnectCancelBtn: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  disconnectCancelText: { fontSize: 14, fontWeight: "600", color: "rgba(255,255,255,0.55)" },
  disconnectConfirmBtn: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#ff4d6d",
  },
  disconnectConfirmText: { fontSize: 14, fontWeight: "700", color: "#fff" },

  // ── Preferences sub-screen ────────────────────────────────────────────────
  prefRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 14,
    marginHorizontal: 12,
    marginTop: 4,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  prefIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(171,0,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  prefLabel: { flex: 1, fontSize: 15, fontWeight: "600", color: "#fff" },
  prefSub:   { fontSize: 12, color: "rgba(255,255,255,0.4)", marginTop: 2 },
});

export const reactStyles = StyleSheet.create({
  floatLayer: {
    position: "absolute",
    right: 18,
    bottom: 84,
    width: 60,
    height: 320,
  },
  heartBtn: {
    width: 44, height: 44, borderRadius: 22,
    backgroundColor: "rgba(233,30,140,0.14)",
    borderWidth: 1, borderColor: "rgba(233,30,140,0.4)",
    alignItems: "center", justifyContent: "center",
  },
  heartEmoji: { fontSize: 22 },
  menuBackdrop: {
    position: "absolute",
    top: -1000, left: -1000, right: -1000, bottom: -1000,
  },
  menu: {
    position: "absolute",
    bottom: 52,
    right: 0,
    backgroundColor: "rgba(20,20,24,0.96)",
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    paddingVertical: 8,
    paddingHorizontal: 6,
    alignItems: "center",
    gap: 2,
  },
  menuItem: {
    width: 44, height: 44, borderRadius: 22,
    alignItems: "center", justifyContent: "center",
  },
  menuEmoji: { fontSize: 24 },
});

export const gdStyles = StyleSheet.create({
  scrim: { backgroundColor: "rgba(0,0,0,0.78)", alignItems: "center", justifyContent: "center", paddingHorizontal: 28 },
  card: { width: "100%", maxWidth: 360, backgroundColor: "#171018", borderRadius: 24, padding: 24, alignItems: "center" },
  iconWrap: { width: 56, height: 56, borderRadius: 28, backgroundColor: "rgba(29,185,84,0.16)", alignItems: "center", justifyContent: "center", marginBottom: 14 },
  title: { fontSize: 20, fontWeight: "800", color: "#fff", marginBottom: 8, textAlign: "center" },
  body: { fontSize: 14, lineHeight: 20, color: "rgba(255,255,255,0.7)", textAlign: "center", marginBottom: 20 },
  toggleRow: { flexDirection: "row", alignItems: "center", gap: 10, alignSelf: "stretch", marginBottom: 20 },
  checkbox: { width: 22, height: 22, borderRadius: 6, borderWidth: 2, borderColor: "rgba(255,255,255,0.35)", alignItems: "center", justifyContent: "center" },
  checkboxOn: { backgroundColor: "#1DB954", borderColor: "#1DB954" },
  toggleText: { fontSize: 14, color: "rgba(255,255,255,0.85)", fontWeight: "600" },
  gotItBtn: { alignSelf: "stretch", backgroundColor: "#1DB954", borderRadius: 26, paddingVertical: 15, alignItems: "center" },
  gotItText: { fontSize: 16, fontWeight: "800", color: "#fff" },
});

export const jpStyles = StyleSheet.create({
  scrim: { flex: 1, backgroundColor: "rgba(0,0,0,0.78)", alignItems: "center", justifyContent: "center", paddingHorizontal: 28 },
  card: { width: "100%", maxWidth: 360, backgroundColor: "#171018", borderRadius: 24, padding: 24, alignItems: "center" },
  iconWrap: { width: 56, height: 56, borderRadius: 28, backgroundColor: "rgba(171,0,255,0.16)", alignItems: "center", justifyContent: "center", marginBottom: 14 },
  title: { fontSize: 20, fontWeight: "800", color: "#fff", marginBottom: 8, textAlign: "center" },
  body: { fontSize: 14, lineHeight: 20, color: "rgba(255,255,255,0.7)", textAlign: "center", marginBottom: 20 },
  publicBtn: { alignSelf: "stretch", flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "#AB00FF", borderRadius: 18, paddingVertical: 14, paddingHorizontal: 16, marginBottom: 12 },
  publicBtnText: { fontSize: 16, fontWeight: "800", color: "#fff" },
  privateBtn: { alignSelf: "stretch", flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "rgba(255,255,255,0.1)", borderRadius: 18, paddingVertical: 14, paddingHorizontal: 16, marginBottom: 8 },
  privateBtnText: { fontSize: 16, fontWeight: "800", color: "#fff" },
  btnSub: { fontSize: 12, color: "rgba(255,255,255,0.65)", marginTop: 2 },
  cancelBtn: { paddingVertical: 12, alignItems: "center", alignSelf: "stretch" },
  cancelText: { fontSize: 15, fontWeight: "700", color: "rgba(255,255,255,0.55)" },
});

export const mbStyles = StyleSheet.create({
  bar: {
    position: "absolute", left: 12, right: 12,
    flexDirection: "row", alignItems: "center", gap: 12,
    backgroundColor: "rgba(20,10,24,0.97)", borderRadius: 16, padding: 10,
    borderWidth: 1, borderColor: "rgba(171,0,255,0.45)",
    shadowColor: "#000", shadowOpacity: 0.4, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 8,
  },
  art: { width: 42, height: 42, borderRadius: 9, backgroundColor: "#222" },
  artFallback: { backgroundColor: "rgba(171,0,255,0.35)", alignItems: "center", justifyContent: "center" },
  titleRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  liveDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#FF3B5C" },
  title: { fontSize: 14, fontWeight: "800", color: "#fff", flexShrink: 1 },
  subtitle: { fontSize: 12, color: "rgba(255,255,255,0.55)", marginTop: 2 },
  expandBtn: { width: 34, height: 34, borderRadius: 17, backgroundColor: "rgba(255,255,255,0.12)", alignItems: "center", justifyContent: "center" },
});

export const llStyles = StyleSheet.create({
  talkBanner: {
    position: "absolute", top: 104, left: 16, right: 16,
    flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8,
    backgroundColor: "rgba(171,0,255,0.85)", borderRadius: 14, paddingVertical: 10,
  },
  talkBannerText: { fontSize: 13, fontWeight: "700", color: "#fff" },
  saveSongBtn: {
    justifyContent: "center", gap: 12, flexDirection: "row", alignItems: "center", 
    backgroundColor: "rgba(29,185,84,0.92)", borderRadius: 24, paddingVertical: 13, paddingHorizontal: 24, marginTop: 20,
  },
  saveSongBtnDone: { backgroundColor: "rgba(29,185,84,0.4)" },
  saveSongText: { fontSize: 14, fontWeight: "800", color: "#fff" },
  syncRow: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: 8, paddingBottom: 20 },
  syncDotOk: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#1DB954" },
  syncTextOk: { fontSize: 12, fontWeight: "600", color: "rgba(255,255,255,0.6)" },
  syncTextBusy: { fontSize: 12, fontWeight: "600", color: "#FFB020" },
  endedOverlay: { backgroundColor: "rgba(0,0,0,0.88)", alignItems: "center", justifyContent: "center", gap: 14 },
  endedTitle: { fontSize: 20, fontWeight: "800", color: "#fff" },
  endedBtn: { backgroundColor: "#AB00FF", borderRadius: 24, paddingHorizontal: 32, paddingVertical: 13, marginTop: 8 },
  endedBtnText: { fontSize: 15, fontWeight: "700", color: "#fff" },
});

export const mcStyles = StyleSheet.create({
  row: { flexDirection: "row", alignItems: "flex-end", gap: 8 },
  avatar: { width: 30, height: 30, borderRadius: 15, flexShrink: 0, backgroundColor: "#222" },
  avatarFallback: { backgroundColor: "rgba(171,0,255,0.4)", alignItems: "center", justifyContent: "center" },
  avatarLetter: { fontSize: 12, fontWeight: "800", color: "#fff" },
  bubble: { backgroundColor: "rgba(243, 243, 243, 0.1)", borderRadius: 14, paddingHorizontal: 12, paddingVertical: 7, flexShrink: 1 },
  name: { fontSize: 13, fontWeight: "700", color: "rgba(255, 255, 255, 0.73)", marginBottom: 1 },
  text: { fontSize: 13, color: "#fff" },
});

export const sumStyles = StyleSheet.create({
  root: { backgroundColor: "#0D0D0D" },
  header: { alignItems: "center", paddingTop: 24, paddingBottom: 8, gap: 6 },
  title: { fontSize: 26, fontWeight: "900", color: "#fff" },
  sub: { fontSize: 14, color: "rgba(255,255,255,0.5)" },
  empty: { fontSize: 14, color: "rgba(255,255,255,0.4)", textAlign: "center", marginTop: 40 },
  trackRow: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "rgba(255,255,255,0.05)", borderRadius: 12, padding: 10 },
  art: { width: 44, height: 44, borderRadius: 8 },
  trackName: { fontSize: 14, fontWeight: "700", color: "#fff" },
  trackArtist: { fontSize: 12, color: "rgba(255,255,255,0.45)", marginTop: 2 },
  rowSaveBtn: { width: 32, alignItems: "center", justifyContent: "center" },
  footer: { padding: 16, gap: 10 },
  saveBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: "#1DB954", borderRadius: 26, paddingVertical: 15 },
  saveBtnDone: { backgroundColor: "rgba(29,185,84,0.45)" },
  saveBtnText: { fontSize: 15, fontWeight: "800", color: "#fff" },
  doneBtn: { alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,0.1)", borderRadius: 26, paddingVertical: 15 },
  doneBtnText: { fontSize: 15, fontWeight: "700", color: "#fff" },
});

export const profileStyles = StyleSheet.create({
  scrollContent: { padding: 10, paddingBottom: NAVBAR_H + BOTTOM_INSET + 32 },

  // Top bar — flat, no border radius
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  topBarTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#ffffff",
    letterSpacing: -0.3,
  },
  topBarRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  topBarIconBtn: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
  },
  topBarIcon: { fontSize: 18, color: "rgba(255,255,255,0.6)" },
  proBadge: {
    paddingHorizontal: 12,
    height: 30,
    borderRadius: 8,
    backgroundColor: "#AB00FF",
    alignItems: "center",
    justifyContent: "center",
  },
  proBadgeText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#fff",
    letterSpacing: 1.2,
  },
  card: { backgroundColor: "#161618", borderRadius: 24, overflow: "hidden", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  bannerWrap: { height: PROFILE_BANNER_H, overflow: "hidden" },
  bannerGlow: { position: "absolute", width: 280, height: 280, borderRadius: 140, backgroundColor: "#FF7030", opacity: 0.38, alignSelf: "center", top: -100 },
  bannerActions: { position: "absolute", bottom: 14, right: 16, flexDirection: "row", alignItems: "center", gap: 8 },
  socialBtn: { width: 34, height: 34, borderRadius: 17, backgroundColor: "rgba(0,0,0,0.35)", borderWidth: 1, borderColor: "rgba(255,255,255,0.18)", alignItems: "center", justifyContent: "center" },
  socialIcon: { fontSize: 15, color: "#fff" },
  followBtn: { paddingHorizontal: 18, height: 34, borderRadius: 17, backgroundColor: "#ffffff", alignItems: "center", justifyContent: "center" },
  followBtnText: { fontSize: 14, fontWeight: "700", color: "#111" },
  editProfileBtn: { paddingHorizontal: 16, height: 34, borderRadius: 17, backgroundColor: "rgba(255,255,255,0.12)", borderWidth: 1, borderColor: "rgba(255,255,255,0.22)", alignItems: "center", justifyContent: "center" },
  editProfileBtnText: { fontSize: 14, fontWeight: "700", color: "#fff" },
  avatarRow: { paddingHorizontal: 18, paddingBottom: 12 },
  avatar: { width: PROFILE_AVATAR_SIZE, height: PROFILE_AVATAR_SIZE, borderRadius: 18, backgroundColor: "#FF6B35", borderWidth: 3, borderColor: "#161618", alignItems: "center", justifyContent: "center" },
  avatarInitials: { fontSize: 28, fontWeight: "800", color: "#fff" },
  infoSection: { paddingHorizontal: 20, paddingBottom: 26 },
  nameRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 3 },
  name: { fontSize: 21, fontWeight: "800", color: "#ffffff" },
  verifiedBadge: { width: 20, height: 20, borderRadius: 10, backgroundColor: "#1D9BF0", alignItems: "center", justifyContent: "center" },
  verifiedText: { fontSize: 10, fontWeight: "900", color: "#fff" },
  handle: { fontSize: 14, color: "rgba(255,255,255,0.4)", marginBottom: 14 },
  bio: { fontSize: 14, color: "rgba(255,255,255,0.8)", lineHeight: 22, marginBottom: 16 },
  mention: { color: "#1D9BF0" },
  statsRow: { flexDirection: "row", alignItems: "baseline", marginBottom: 16 },
  statNum: { fontSize: 15, fontWeight: "800", color: "#ffffff" },
  statLabel: { fontSize: 14, color: "rgba(255,255,255,0.38)" },
  metaRow: { flexDirection: "row", gap: 20, flexWrap: "wrap" },
  metaItem: { flexDirection: "row", alignItems: "center", gap: 5, flex: 1, maxWidth: "55%" },
  metaIcon: { fontSize: 13, color: "rgba(255,255,255,0.28)" },
  metaText: { fontSize: 13, color: "rgba(255,255,255,0.32)" },
  linkBadge: { backgroundColor: "rgba(255,108,26,0.18)", borderRadius: 8, paddingHorizontal: 5, paddingVertical: 1 },
  linkBadgeText: { fontSize: 10, fontWeight: "800", color: "#FF6C1A" },

  // Spotify reconnect
  reconnectCard: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(29,185,84,0.08)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(29,185,84,0.2)",
    padding: 14,
  },
  reconnectTitle: { fontSize: 14, fontWeight: "700", color: "#fff" },
  reconnectSub: { fontSize: 12, color: "rgba(255,255,255,0.4)", marginTop: 2 },

  // Now Playing card
  nowPlayingCard: {
    marginTop: 12,
    borderRadius: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    padding: 16,
    gap: 14,
  },
  nowPlayingCardMeet: { borderColor: "rgba(171,0,255,0.45)" },
  npMeetBadge: {
    flexDirection: "row", alignItems: "center", gap: 7,
    alignSelf: "flex-start",
    backgroundColor: "rgba(171,0,255,0.22)",
    borderRadius: 999, paddingVertical: 6, paddingHorizontal: 12,
    marginBottom: 2,
  },
  npMeetBadgeText: { fontSize: 12, fontWeight: "700", color: "#E7CBFF", flexShrink: 1 },
  npMeetBadgeHost: { fontWeight: "800", color: "#fff" },
  npTopRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  npArt: {
    width: 68,
    height: 68,
    borderRadius: 10,
    backgroundColor: "#2a1a10",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  npArtFallback: { backgroundColor: "#2a1a10", alignItems: "center", justifyContent: "center" },
  npArtEmoji: { fontSize: 26, opacity: 0.5 },
  npInfo: { flex: 1, gap: 3 },
  npTitle: { fontSize: 15, fontWeight: "700", color: "#ffffff" },
  npArtist: { fontSize: 13, color: "rgba(255,255,255,0.45)", marginBottom: 10 },
  npProgressTrack: { height: 3, backgroundColor: "rgba(255,255,255,0.15)", borderRadius: 2, marginBottom: 5 },
  npProgressFill: { width: "35%", height: 3, backgroundColor: "#ffffff", borderRadius: 2, position: "relative" },
  npProgressThumb: { position: "absolute", right: -5, top: -4, width: 11, height: 11, borderRadius: 6, backgroundColor: "#fff" },
  npTimestamps: { flexDirection: "row", justifyContent: "space-between" },
  npTime: { fontSize: 11, color: "rgba(255,255,255,0.35)" },

  // Section tabs
  tabsWrap: { marginTop: 10 },
  tabRow: {
    flexDirection: "row",
    position: "relative",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.07)",
  },
  tabIndicator: {
    position: "absolute",
    bottom: 0,
    height: 2,
    borderRadius: 1,
    overflow: "hidden",
  },
  tabBtn: {
    paddingVertical: 12,
    alignItems: "center",
  },
  tabLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "rgba(255,255,255,0.32)",
    letterSpacing: 0.2,
  },
  tabLabelActive: {
    color: "#ffffff",
  },
  // Repost label
  repostLabel: { paddingHorizontal: 12, paddingBottom: 6, paddingTop: 2 },
  repostLabelText: { fontSize: 12, color: "rgba(255,255,255,0.35)", fontWeight: "600" },

  // Playlist list items
  playlistListItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderRadius: 14,
  },
  playlistListArt: {
    width: 56,
    height: 56,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
  },
  playlistListArtInner: { ...StyleSheet.absoluteFillObject, flexDirection: "row", flexWrap: "wrap" },
  playlistListMiniCell: { width: "50%", height: "100%" },
  playlistListName: { fontSize: 15, fontWeight: "700", color: "#fff", marginBottom: 3 },
  playlistListMeta: { fontSize: 13, color: "rgba(255,255,255,0.38)" },
  playlistChevron: { fontSize: 20, color: "rgba(255,255,255,0.25)", paddingRight: 4 },

  // Community cards
  communityCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
  },
  communityIcon: {
    width: 46,
    height: 46,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  communityName: { fontSize: 14, fontWeight: "700", color: "#fff", marginBottom: 3 },
  communityDesc: { fontSize: 12, color: "rgba(255,255,255,0.4)" },
  communityMembers: { fontSize: 13, fontWeight: "700", flexShrink: 0 },

  // Gradient toggle
  toggleTrack: {
    width: TOGGLE_W,
    height: TOGGLE_H,
    borderRadius: TOGGLE_H / 2,
    overflow: "hidden",
    justifyContent: "center",
    paddingLeft: 3,
  },
  toggleThumb: {
    width: THUMB_SIZE,
    height: THUMB_SIZE,
    borderRadius: THUMB_SIZE / 2,
    backgroundColor: "#ffffff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 3,
  },

  // Broadcast row
  broadcastRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  broadcastLabel: {
    fontSize: 14,
    color: "rgba(255,255,255,0.6)",
    fontWeight: "500",
  },

  // Start Meet button — lives inside the Now Playing card
  startMeetBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    marginTop: 12,
    paddingVertical: 11,
    borderRadius: 18,
    backgroundColor: "rgba(0,0,0,0.28)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
  },
  startMeetBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#fff",
    letterSpacing: 0.2,
  },

  // Sticky compose FAB + its option menu
  fab: {
    position: "absolute",
    right: 18,
    bottom: NAVBAR_H + BOTTOM_INSET + 14,
    width: 58, height: 58, borderRadius: 29,
    backgroundColor: "#FF6C1A",
    alignItems: "center", justifyContent: "center",
    shadowColor: "#FF6C1A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.45,
    shadowRadius: 12,
    elevation: 8,
  },
  fabMenuOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
    alignItems: "flex-end",
    paddingRight: 18,
    paddingBottom: NAVBAR_H + BOTTOM_INSET + 82,
  },
  fabMenu: {
    width: 270,
    backgroundColor: "#1A1A1C",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingVertical: 6,
    overflow: "hidden",
  },
  fabMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  fabMenuIcon: {
    width: 40, height: 40, borderRadius: 12,
    backgroundColor: "rgba(255,108,26,0.12)",
    alignItems: "center", justifyContent: "center",
  },
  fabMenuTitle: { fontSize: 15, fontWeight: "700", color: "#fff" },
  fabMenuSub: { fontSize: 12, color: "rgba(255,255,255,0.45)", marginTop: 2 },
  fabMenuDivider: { height: 1, backgroundColor: "rgba(255,255,255,0.07)", marginHorizontal: 16 },
});

export const mmStyles = StyleSheet.create({
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.70)",
  },
  sheet: {
    // Fixed height anchored to the bottom. Keyboard slides over the bottom portion;
    // the inner ScrollView lets the user reach everything by scrolling.
    position: "absolute",
    bottom: 0, left: 0, right: 0,
    height: SH * 0.85,
    backgroundColor: "#111113",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: "hidden",
    borderTopWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  handle: {
    width: 40, height: 4, borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignSelf: "center",
    marginTop: 10,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.07)",
  },
  headerTitle: { fontSize: 17, fontWeight: "700", color: "#fff" },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 40, paddingTop: 8 },

  label: {
    fontSize: 13,
    fontWeight: "600",
    color: "rgba(255,255,255,0.55)",
    marginTop: 18,
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  labelMuted: { fontWeight: "400", textTransform: "none", letterSpacing: 0 },

  input: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: "#fff",
  },
  inputMultiline: {
    minHeight: 88,
    textAlignVertical: "top",
  },

  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  toggleLabel: { fontSize: 15, color: "#fff", fontWeight: "500" },

  tagInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  tagInput: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 15,
    color: "#fff",
  },
  tagAddBtn: {
    width: 44, height: 44, borderRadius: 14,
    backgroundColor: "rgba(171,0,255,0.18)",
    borderWidth: 1,
    borderColor: "rgba(171,0,255,0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  tagChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  tagChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(171,0,255,0.14)",
    borderWidth: 1,
    borderColor: "rgba(171,0,255,0.32)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  tagChipText: { fontSize: 13, color: "#AB00FF", fontWeight: "600" },

  startBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginTop: 28,
    paddingVertical: 15,
    borderRadius: 24,
    backgroundColor: "#AB00FF",
  },
  startBtnDisabled: { opacity: 0.40 },
  startBtnText: { fontSize: 16, fontWeight: "700", color: "#fff" },
});

export const mlStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#000" },

  // ── Top bar ───────────────────────────────────────────────────────────────
  topBar: {
    position: "absolute",
    top: 0, left: 0, right: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingTop: 52,
    paddingBottom: 10,
  },
  topLeft:  { flexDirection: "row", alignItems: "center", gap: 10 },
  topRight: { flexDirection: "row", alignItems: "center", gap: 8 },

  // Gradient-ring avatar (like in image)
  avatarRing: {
    width: 44, height: 44, borderRadius: 22,
    padding: 2.5,
    alignItems: "center", justifyContent: "center",
  },
  avatarInner: {
    flex: 1, width: "100%", borderRadius: 18,
    backgroundColor: "#1c0030",
    alignItems: "center", justifyContent: "center",
  },
  avatarInitial: { fontSize: 15, fontWeight: "800", color: "#fff" },
  hostName:      { fontSize: 16, fontWeight: "700", color: "#fff" },
  listenerRow:   { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 2 },
  liveDotSm:     { width: 6, height: 6, borderRadius: 3, backgroundColor: "#FF3B30" },
  listenerText:  { fontSize: 12, color: "rgba(255,255,255,0.7)", fontWeight: "600" },

  // Dark circular buttons — exactly as in image
  topCircle: {
    width: 38, height: 38, borderRadius: 19,
    backgroundColor: "rgba(45,45,45,0.82)",
    alignItems: "center", justifyContent: "center",
  },
  endBtn: {
    paddingHorizontal: 16, height: 38, borderRadius: 19,
    backgroundColor: "#E8000F",
    alignItems: "center", justifyContent: "center",
  },
  endBtnText: { fontSize: 13, fontWeight: "800", color: "#fff" },
  micBtn: {
    width: 52, height: 52, borderRadius: 26,
    backgroundColor: "rgba(45,45,45,0.82)",
    alignItems: "center", justifyContent: "center",
  },
  micBtnOn: { backgroundColor: "#AB00FF" },

  // ── Comments + hearts row ────────────────────────────────────────────────
  commentSection: {
    position: "absolute",
    left: 0, right: 0,
    bottom: BOTTOM_INSET + 76,   // sits above bottom bar
    flexDirection: "row",
    alignItems: "flex-end",
    paddingLeft: 14,
    paddingRight: 10,
  },
  commentCol: { flex: 1, gap: 9 },

  msgRow: { flexDirection: "row", alignItems: "center", gap: 8 },

  msgAvatar: {
    width: 34, height: 34, borderRadius: 17,
    alignItems: "center", justifyContent: "center",
    flexShrink: 0,
  },
  msgAvatarLetter: { fontSize: 13, fontWeight: "800", color: "#fff" },

  msgBubble: {
    backgroundColor: "rgba(255,255,255,0.78)",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 9,
    flexShrink: 1,
  },
  msgName: { fontSize: 12, fontWeight: "700", color: "#fff",                   marginBottom: 2 },
  msgText: { fontSize: 13, fontWeight: "400", color: "rgba(255,255,255,0.88)" },

  // Hearts aligned to bottom-right of the comment stack
  heartsCol: {
    alignItems: "center",
    justifyContent: "flex-end",
    paddingBottom: 4,
    paddingLeft: 4,
    gap: 8,
  },
  heartLg: { fontSize: 26 },
  heartSm: { fontSize: 18, opacity: 0.70 },

  // ── Bottom bar ────────────────────────────────────────────────────────────
  bottomBarWrap: {
    position: "absolute",
    bottom: 0, left: 0, right: 0,
  },
  bottomBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: BOTTOM_INSET + 16,
    gap: 14,
  },
  // White pill — exactly as in image
  inputPill: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(45,45,45,0.70)",
    borderRadius: 30,
    paddingHorizontal: 18,
    paddingVertical: 14,
    gap: 10,
  },
  inputPlaceholder: { fontSize: 15, color: "rgba(255,255,255,0.32)" },
  inputField: { flex: 1, fontSize: 15, color: "#fff", padding: 0 },
  // Icons are standalone — no container — matching the image

  // ── Swipe hint (right edge of page 1) ────────────────────────────────────
  swipeHint: {
    position: "absolute",
    right: 12,
    top: SH * 0.52,
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    opacity: 0.5,
  },
  swipeHintText: {
    fontSize: 11,
    fontWeight: "600",
    color: "rgb(255,255,255)",
    letterSpacing: 0.5,
  },

  // ── Page 2 — Music picker ─────────────────────────────────────────────────
  musicPage: {
    width: SW,
    height: SH,
    backgroundColor: "#0e0e11",
    flexDirection: "column",   // explicit — children stack vertically
  },
  musicHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 56,
    paddingBottom: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.07)",
  },
  musicBackBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  musicTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#fff",
  },
  musicSearchRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.07)",
    borderRadius: 14,
    marginHorizontal: 16,
    marginTop: 14,
    marginBottom: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  musicSearchInput: {
    flex: 1,
    fontSize: 15,
    color: "#fff",
    paddingVertical: 0,
  },
  musicListContent: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: BOTTOM_INSET + 24,
  },
  musicRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.05)",
  },
  musicRowArt: {
    width: 50,
    height: 50,
    borderRadius: 8,
    flexShrink: 0,
  },
  musicRowName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#fff",
    marginBottom: 3,
  },
  musicRowSub: {
    fontSize: 12,
    color: "rgba(255,255,255,0.45)",
  },
  musicEmpty: {
    textAlign: "center",
    marginTop: 48,
    fontSize: 14,
    color: "rgba(255,255,255,0.3)",
  },

  // ── Track info + playback controls ───────────────────────────────────────
  trackSection: {
    position: "absolute",
    left: 0,
    right: 0,
    // Sits between top bar and comments; centres in the usable space
    top: SH * 0.30,
    alignItems: "center",
    paddingHorizontal: 32,
  },
  trackName: {
    fontSize: 22,
    fontWeight: "800",
    color: "#fff",
    textAlign: "center",
    textShadowColor: "rgba(0,0,0,0.6)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
    marginBottom: 4,
  },
  trackArtist: {
    fontSize: 14,
    fontWeight: "500",
    color: "rgba(255,255,255,0.72)",
    textAlign: "center",
    textShadowColor: "rgba(0,0,0,0.5)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
    marginBottom: 20,
  },
  // Thin progress bar (full width of section)
  progressTrack: {
    width: "100%",
    height: 3,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.22)",
    overflow: "hidden",
    marginBottom: 6,
  },
  progressFill: {
    height: "100%",
    borderRadius: 2,
    backgroundColor: "#fff",
  },
  progressTimes: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 28,
  },
  progressTime: {
    fontSize: 11,
    color: "rgba(255,255,255,0.55)",
  },
  // Prev / Play-Pause / Next row
  controls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 36,
  },
  // Circular play/pause button
  playBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "rgba(255,255,255,0.18)",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.55)",
    alignItems: "center",
    justifyContent: "center",
  },
});

export const csStyles = StyleSheet.create({
  backdrop: { backgroundColor: "rgba(0,0,0,0.65)" },
  sheet: {
    position: "absolute", bottom: 0, left: 0, right: 0, height: "90%",
    backgroundColor: "#111113",
    borderTopLeftRadius: 26, borderTopRightRadius: 26,
    overflow: "hidden",
    borderTopWidth: 1, borderColor: "rgba(255,255,255,0.08)",
  },
  header: {
    flexDirection: "row", alignItems: "center", justifyContent: "space-between",
    paddingHorizontal: 18, paddingVertical: 14,
    borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.07)",
  },
  title: { fontSize: 16, fontWeight: "700", color: "#fff" },
  cancelBtn: { fontSize: 15, color: "rgba(255,255,255,0.5)" },
  postBtn: {
    backgroundColor: "#AB00FF", borderRadius: 20,
    paddingHorizontal: 18, paddingVertical: 7,
    minWidth: 56, alignItems: "center",
  },
  postBtnText: { fontSize: 14, fontWeight: "700", color: "#fff" },

  composeRow: { flexDirection: "row", alignItems: "flex-start", padding: 18, gap: 12 },
  avatar: {
    width: 42, height: 42, borderRadius: 12,
    backgroundColor: "#AB00FF",
    alignItems: "center", justifyContent: "center", flexShrink: 0,
    overflow: "hidden",
  },
  avatarInitials: { fontSize: 16, fontWeight: "800", color: "#fff" },
  textInput: {
    flex: 1, fontSize: 16, color: "#fff",
    lineHeight: 24, minHeight: 80,
    textAlignVertical: "top",
  },

  imageStrip: { paddingHorizontal: 18, paddingBottom: 16, gap: 10, flexDirection: "row", alignItems: "center" },
  thumbImage: { width: 88, height: 88, borderRadius: 12 },
  thumbRemove: {
    position: "absolute", top: 4, right: 4,
    width: 22, height: 22, borderRadius: 11,
    backgroundColor: "rgba(0,0,0,0.65)",
    alignItems: "center", justifyContent: "center",
  },
  thumbRemoveText: { color: "#fff", fontSize: 11, fontWeight: "700" },
  thumbAdd: {
    width: 88, height: 88, borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1, borderColor: "rgba(255,255,255,0.12)",
    borderStyle: "dashed",
    alignItems: "center", justifyContent: "center",
  },

  pollSection: { paddingHorizontal: 18, paddingBottom: 12, gap: 10 },
  pollQuestion: {
    backgroundColor: "#1A1A1C", borderRadius: 14,
    borderWidth: 1, borderColor: "rgba(255,255,255,0.1)",
    color: "#fff", fontSize: 16, fontWeight: "600",
    paddingHorizontal: 16, paddingVertical: 13,
  },
  pollOptionRow: { flexDirection: "row", alignItems: "center" },
  pollOptionInput: {
    flex: 1, backgroundColor: "#1A1A1C", borderRadius: 12,
    borderWidth: 1, borderColor: "rgba(255,255,255,0.08)",
    color: "#fff", fontSize: 14,
    paddingHorizontal: 14, paddingVertical: 11,
  },
  addOptionBtn: {
    flexDirection: "row", alignItems: "center",
    paddingVertical: 10, paddingHorizontal: 4,
  },
  addOptionText: { fontSize: 14, color: "#AB00FF", fontWeight: "600" },

  toolbar: {
    flexDirection: "row", alignItems: "center",
    paddingHorizontal: 16, paddingVertical: 12,
    borderTopWidth: 1, borderTopColor: "rgba(255,255,255,0.07)",
    gap: 4,
  },
  toolBtn: {
    width: 44, height: 44, borderRadius: 22,
    alignItems: "center", justifyContent: "center",
  },
  toolBtnActive: { backgroundColor: "rgba(171,0,255,0.12)" },
  audienceChip: {
    flexDirection: "row", alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.07)",
    borderRadius: 16, paddingHorizontal: 12, paddingVertical: 6,
    borderWidth: 1, borderColor: "rgba(255,255,255,0.1)",
  },
  audienceText: { fontSize: 13, color: "rgba(255,255,255,0.5)", fontWeight: "600" },

  // ─── Media source picker panel ──────────────────────────────────────────────
  mediaPicker: {
    flexDirection: "row", alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(255,255,255,0.12)",
    paddingVertical: 16, paddingHorizontal: 16,
  },
  mediaPickerBtn: { flex: 1, alignItems: "center", gap: 7 },
  mediaPickerLabel: { color: "#fff", fontSize: 12, fontWeight: "600", opacity: 0.85 },
  mediaPickerDivider: {
    width: StyleSheet.hairlineWidth, height: 38,
    backgroundColor: "rgba(255,255,255,0.15)", marginHorizontal: 6,
  },
  mediaPickerClose: { paddingLeft: 14, paddingRight: 2, alignSelf: "center" },
});

export const psStyles = StyleSheet.create({
  sheet: { position: "absolute", bottom: 0, left: 0, right: 0, height: "88%", backgroundColor: "#111113", borderTopLeftRadius: 28, borderTopRightRadius: 28, overflow: "hidden", borderTopWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  navBtn: { width: 32, alignItems: "center" },
  homeContent: { paddingHorizontal: 20, paddingTop: 22, paddingBottom: 40 },
  sectionLabel: { fontSize: 11, fontWeight: "700" as const, color: "rgba(255,255,255,0.3)", letterSpacing: 1, marginBottom: 14 },
  nowPlayingCard: { flexDirection: "row" as const, alignItems: "center" as const, gap: 12, backgroundColor: "rgba(29,185,84,0.08)", borderRadius: 16, borderWidth: 1, borderColor: "rgba(29,185,84,0.2)", padding: 14 },
  npArt: { width: 52, height: 52, borderRadius: 10, flexShrink: 0 },
  npArtFallback: { backgroundColor: "rgba(255,255,255,0.06)", alignItems: "center" as const, justifyContent: "center" as const },
  npTrack: { fontSize: 14, fontWeight: "700" as const, color: "#fff" },
  npArtist: { fontSize: 12, color: "rgba(255,255,255,0.5)", marginTop: 2 },
  pinBtn: { flexDirection: "row" as const, alignItems: "center" as const, gap: 5, backgroundColor: "#1DB954", borderRadius: 10, paddingHorizontal: 12, paddingVertical: 7 },
  pinBtnText: { fontSize: 12, fontWeight: "700" as const, color: "#000" },
  addSongBtn: { flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "center" as const, gap: 10, backgroundColor: "#FF6C1A", borderRadius: 14, paddingVertical: 14 },
  addSongText: { fontSize: 15, fontWeight: "700" as const, color: "#fff" },
  divider: { height: 1, backgroundColor: "rgba(255,255,255,0.07)", marginVertical: 24 },
  menuRow: { flexDirection: "row" as const, alignItems: "center" as const, gap: 14, paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.05)" },
  menuIcon: { width: 40, height: 40, borderRadius: 12, alignItems: "center" as const, justifyContent: "center" as const },
  menuLabel: { flex: 1, fontSize: 15, fontWeight: "600" as const, color: "#fff" },
  plArt: { width: 48, height: 48, borderRadius: 8, flexShrink: 0 },
  likedArt: { backgroundColor: "rgba(29,185,84,0.1)", alignItems: "center" as const, justifyContent: "center" as const },
  plArtFallback: { backgroundColor: "rgba(255,255,255,0.06)", alignItems: "center" as const, justifyContent: "center" as const },
  // Preview step
  previewWrap: { flex: 1, alignItems: "center" as const, paddingHorizontal: 28, paddingTop: 20, paddingBottom: 28 },
  previewArt: { width: 190, height: 190, borderRadius: 18, marginBottom: 22 },
  previewArtFallback: { backgroundColor: "rgba(255,255,255,0.06)", alignItems: "center" as const, justifyContent: "center" as const },
  previewTrack: { fontSize: 20, fontWeight: "800" as const, color: "#fff", textAlign: "center" as const, marginBottom: 6 },
  previewArtist: { fontSize: 14, color: "rgba(255,255,255,0.45)", textAlign: "center" as const, marginBottom: 24 },
  previewProgressTrack: { width: "100%", height: 4, backgroundColor: "rgba(255,255,255,0.12)", borderRadius: 2, marginBottom: 8 },
  previewProgressFill: { height: 4, backgroundColor: "#1DB954", borderRadius: 2 },
  previewTimes: { width: "100%", flexDirection: "row" as const, justifyContent: "space-between" as const, marginBottom: 20 },
  previewTime: { fontSize: 11, color: "rgba(255,255,255,0.35)", fontWeight: "600" as const },
  noPreviewText: { fontSize: 13, color: "rgba(255,255,255,0.3)", marginVertical: 24, fontStyle: "italic" as const },
  playPauseBtn: { width: 60, height: 60, borderRadius: 30, backgroundColor: "#1DB954", alignItems: "center" as const, justifyContent: "center" as const, marginBottom: 28 },
  previewActions: { flexDirection: "row" as const, gap: 12, width: "100%", marginBottom: 14 },
  openBtn: { flex: 1, flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "center" as const, gap: 7, height: 46, borderRadius: 14, backgroundColor: "rgba(29,185,84,0.12)", borderWidth: 1, borderColor: "rgba(29,185,84,0.3)" },
  openBtnText: { fontSize: 14, fontWeight: "700" as const, color: "#1DB954" },
  saveBtn: { flex: 1, flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "center" as const, gap: 7, height: 46, borderRadius: 14, backgroundColor: "rgba(255,255,255,0.07)", borderWidth: 1, borderColor: "rgba(255,255,255,0.14)" },
  saveBtnSaved: { backgroundColor: "rgba(29,185,84,0.1)", borderColor: "rgba(29,185,84,0.28)" },
  saveBtnText: { fontSize: 14, fontWeight: "600" as const, color: "rgba(255,255,255,0.7)" },
  saveBtnTextSaved: { color: "#1DB954" },
  pinCTA: { flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "center" as const, gap: 8, width: "100%", height: 52, borderRadius: 16, backgroundColor: "#FF6C1A" },
  pinCTAText: { fontSize: 16, fontWeight: "800" as const, color: "#000" },
});

export const epOverlayStyles = StyleSheet.create({
  backdrop: { backgroundColor: "rgba(0,0,0,0.70)" },
  sheet: {
    position: "absolute", bottom: 0, left: 0, right: 0, height: "92%",
    backgroundColor: "#111113",
    borderTopLeftRadius: 28, borderTopRightRadius: 28,
    overflow: "hidden",
    borderTopWidth: 1, borderColor: "rgba(255,255,255,0.08)",
  },
  songSheet: {
    position: "absolute", bottom: 0, left: 0, right: 0, height: "75%",
    backgroundColor: "#111113",
    borderTopLeftRadius: 24, borderTopRightRadius: 24,
    overflow: "hidden",
    borderTopWidth: 1, borderColor: "rgba(255,255,255,0.08)",
    paddingBottom: 20,
  },
  handle: { width: 36, height: 4, borderRadius: 2, backgroundColor: "rgba(255,255,255,0.15)", alignSelf: "center", marginTop: 10, marginBottom: 4 },
  sheetHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 20, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.07)" },
  sheetTitle: { fontSize: 16, fontWeight: "700", color: "#fff" },
  closeBtn: { fontSize: 16, color: "rgba(255,255,255,0.45)", fontWeight: "600" },
  cancelBtn: { fontSize: 15, color: "rgba(255,255,255,0.5)" },
  saveBtn: { fontSize: 15, fontWeight: "700", color: "#FF6C1A" },
  searchRow: { flexDirection: "row", alignItems: "center", margin: 16, backgroundColor: "#1A1A1C", borderRadius: 14, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", paddingHorizontal: 14, paddingVertical: 11 },
  searchInput: { flex: 1, color: "#fff", fontSize: 15 },
  resultRow: { flexDirection: "row", alignItems: "center", paddingHorizontal: 16, paddingVertical: 10, gap: 12, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.04)" },
  resultArt: { width: 46, height: 46, borderRadius: 8 },
  resultArtFallback: { backgroundColor: "rgba(255,255,255,0.06)", alignItems: "center", justifyContent: "center" },
  resultTrack: { fontSize: 14, fontWeight: "600", color: "#fff" },
  resultArtist: { fontSize: 12, color: "rgba(255,255,255,0.45)", marginTop: 2 },
  emptyText: { textAlign: "center", color: "rgba(255,255,255,0.25)", fontSize: 14, marginTop: 32 },
  avatarSection: { alignItems: "center", paddingVertical: 24 },
  avatarWrap: { position: "relative", width: 94, height: 94 },
  avatarCircle: { width: 90, height: 90, borderRadius: 20, backgroundColor: "#FF6B35", alignItems: "center", justifyContent: "center", overflow: "hidden" },
  avatarLoading: { backgroundColor: "rgba(255,255,255,0.1)" },
  avatarInitials: { fontSize: 30, fontWeight: "800", color: "#fff" },
  avatarEditBadge: { position: "absolute", bottom: -4, right: -4, width: 26, height: 26, borderRadius: 13, backgroundColor: "#FF6C1A", borderWidth: 2, borderColor: "#111113", alignItems: "center", justifyContent: "center" },
  avatarHint: { marginTop: 10, fontSize: 12, color: "rgba(255,255,255,0.3)" },
  section: { paddingHorizontal: 20, marginBottom: 22 },
  sectionLabel: { fontSize: 11, fontWeight: "700", letterSpacing: 1, color: "rgba(255,255,255,0.3)", marginBottom: 8 },
  input: { backgroundColor: "#1A1A1C", borderRadius: 14, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", color: "#fff", fontSize: 15, paddingHorizontal: 16, paddingVertical: 13 },
  inputMulti: { minHeight: 80, paddingTop: 13, textAlignVertical: "top" },
  songRow: { flexDirection: "row", alignItems: "center", backgroundColor: "#1A1A1C", borderRadius: 14, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", padding: 12, gap: 12 },
  songArt: { width: 44, height: 44, borderRadius: 8 },
  songArtFallback: { backgroundColor: "rgba(255,255,255,0.06)", alignItems: "center", justifyContent: "center" },
  songName: { fontSize: 14, fontWeight: "600", color: "#fff" },
  songArtist: { fontSize: 12, color: "rgba(255,255,255,0.45)", marginTop: 2 },
  songPlaceholder: { fontSize: 14, color: "rgba(255,255,255,0.3)" },
  clearBtn: { marginTop: 8, alignSelf: "flex-start" },
  clearBtnText: { fontSize: 13, color: "rgba(255,100,80,0.7)" },
  linkRow: { flexDirection: "row", alignItems: "center", backgroundColor: "#1A1A1C", borderRadius: 12, borderWidth: 1, borderColor: "rgba(255,255,255,0.08)", paddingHorizontal: 14, paddingVertical: 11, marginBottom: 8, gap: 8 },
  linkText: { flex: 1, fontSize: 13, color: "rgba(255,255,255,0.65)" },
  linkInputRow: { flexDirection: "row", gap: 10, marginTop: 4 },
  linkInput: { flex: 1, backgroundColor: "#1A1A1C", borderRadius: 12, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", color: "#fff", fontSize: 14, paddingHorizontal: 14, paddingVertical: 11 },
  addLinkBtn: { width: 42, height: 42, borderRadius: 12, backgroundColor: "#FF6C1A", alignItems: "center", justifyContent: "center" },
  socialRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 10 },
  socialIconWrap: { width: 40, height: 40, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  socialInput: { flex: 1, backgroundColor: "#1A1A1C", borderRadius: 12, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", color: "#fff", fontSize: 13, paddingHorizontal: 12, paddingVertical: 10 },
  bannerPreview: { height: 150, borderRadius: 14, overflow: "hidden", backgroundColor: "#1A1A1C", alignItems: "flex-end", justifyContent: "flex-end", padding: 10 },
  bannerEditBtn: { flexDirection: "row", alignItems: "center", gap: 5, backgroundColor: "rgba(0,0,0,0.52)", borderRadius: 10, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1, borderColor: "rgba(255,255,255,0.2)" },
  bannerEditText: { fontSize: 12, fontWeight: "700" as const, color: "#fff" },
  inputLocked: { opacity: 0.4 },
  cooldownBadge: { fontSize: 11, fontWeight: "600" as const, color: "#FF6C1A", letterSpacing: 0 },
  cooldownBadgeLocked: { fontSize: 11, fontWeight: "600" as const, color: "rgba(255,100,80,0.75)", letterSpacing: 0 },
});

export const bcOverlayStyles = StyleSheet.create({
  backdrop: { backgroundColor: "rgba(0,0,0,0.6)" },
  sheet: { position: "absolute", bottom: 0, left: 0, right: 0, height: "75%", backgroundColor: "#1A1A1C", borderTopLeftRadius: 24, borderTopRightRadius: 24, overflow: "hidden", borderTopWidth: 1, borderColor: "rgba(255,255,255,0.1)" },
  handle: { width: 36, height: 4, borderRadius: 2, backgroundColor: "rgba(255,255,255,0.15)", alignSelf: "center", marginTop: 10, marginBottom: 4 },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 20, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.07)" },
  title: { fontSize: 16, fontWeight: "700" as const, color: "#fff" },
  closeBtn: { fontSize: 16, color: "rgba(255,255,255,0.45)", fontWeight: "600" as const },
  content: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 40 },
  imageBox: { height: 120, borderRadius: 16, borderWidth: 1.5, borderColor: "rgba(255,255,255,0.15)", borderStyle: "dashed" as const, alignItems: "center", justifyContent: "center", gap: 8, overflow: "hidden", backgroundColor: "#1A1A1C" },
  imageOverlay: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundColor: "rgba(0,0,0,0.45)", alignItems: "center", justifyContent: "center", gap: 6 },
  imageBoxText: { fontSize: 14, color: "rgba(255,255,255,0.5)", fontWeight: "600" as const },
  dividerRow: { flexDirection: "row", alignItems: "center", marginVertical: 22, gap: 12 },
  dividerLine: { flex: 1, height: 1, backgroundColor: "rgba(255,255,255,0.08)" },
  dividerText: { fontSize: 12, color: "rgba(255,255,255,0.25)", fontWeight: "600" as const },
  colorRow: { flexDirection: "row" as const, justifyContent: "space-between" as const, marginBottom: 10 },
  colorSwatch: { borderRadius: 14, alignItems: "center" as const, justifyContent: "center" as const },
  colorSwatchSelected: { borderWidth: 2.5, borderColor: "#fff" },
});

export const bsOverlayStyles = StyleSheet.create({
  sheet: { position: "absolute", bottom: 0, left: 0, right: 0, height: "78%", backgroundColor: "#1A1A1C", borderTopLeftRadius: 24, borderTopRightRadius: 24, overflow: "hidden", borderTopWidth: 1, borderColor: "rgba(255,255,255,0.1)" },
  sectionLabel: { fontSize: 11, fontWeight: "700" as const, color: "rgba(255,255,255,0.35)", letterSpacing: 1, marginBottom: 14 },
  shapeCell: { height: SWATCH_SIZE + 26, borderRadius: 14, backgroundColor: "rgba(255,255,255,0.07)", alignItems: "center" as const, justifyContent: "center" as const },
  shapeCellSelected: { backgroundColor: "rgba(255,108,26,0.18)", borderWidth: 1.5, borderColor: "#FF6C1A" },
  shapeIconWrap: { flex: 1, alignItems: "center" as const, justifyContent: "center" as const },
  shapeLabel: { fontSize: 10, color: "rgba(255,255,255,0.4)", fontWeight: "600" as const, paddingBottom: 7 },
  shapeLabelSelected: { color: "#FF6C1A" },
  disabledHint: { fontSize: 12, color: "rgba(255,255,255,0.35)", textAlign: "center" as const, marginBottom: 14, fontStyle: "italic" as const },
});
