import { StyleSheet, Platform, Dimensions } from "react-native";
import { SW, SH, NAVBAR_H, BOTTOM_INSET, COMPOSER_ABOVE_NAV, COLLAGE_W, COLLAGE_GAP } from "../../../lib/feed/dimensions";
import { STREAM_CARD_GAP, STREAM_CARD_W, WAVE_HEIGHTS, CARD_AVATAR_SIZE, CARD_AVATAR_OVERLAP, CARD_BANNER_H, MSG_HEADER_H, TOGGLE_W, TOGGLE_H, THUMB_SIZE, THUMB_TRAVEL, PROFILE_BANNER_H, PROFILE_AVATAR_SIZE, PROFILE_AVATAR_OVERLAP, SWATCH_SIZE } from "../../../constants/feedLayout";

// Component-scoped StyleSheets extracted from app/feed.tsx.

/** Used by components/profile/EditProfileOverlay.tsx. */
export const epOverlayStyles = StyleSheet.create({
  backdrop: { backgroundColor: "rgba(0,0,0,0.70)" },
  sheet: {
    position: "absolute", bottom: 0, left: 0, right: 0, height: "92%",
    backgroundColor: "#111113",
    borderTopLeftRadius: 28, borderTopRightRadius: 28,
    overflow: "hidden",
    borderTopWidth: 1, borderColor: "rgba(255,255,255,0.08)",
  },
  songSheet: {
    position: "absolute", bottom: 0, left: 0, right: 0, height: "75%",
    backgroundColor: "#111113",
    borderTopLeftRadius: 24, borderTopRightRadius: 24,
    overflow: "hidden",
    borderTopWidth: 1, borderColor: "rgba(255,255,255,0.08)",
    paddingBottom: 20,
  },
  handle: { width: 36, height: 4, borderRadius: 2, backgroundColor: "rgba(255,255,255,0.15)", alignSelf: "center", marginTop: 10, marginBottom: 4 },
  sheetHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 20, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.07)" },
  sheetTitle: { fontSize: 16, fontWeight: "700", color: "#fff" },
  closeBtn: { fontSize: 16, color: "rgba(255,255,255,0.45)", fontWeight: "600" },
  cancelBtn: { fontSize: 15, color: "rgba(255,255,255,0.5)" },
  saveBtn: { fontSize: 15, fontWeight: "700", color: "#FF6C1A" },
  searchRow: { flexDirection: "row", alignItems: "center", margin: 16, backgroundColor: "#1A1A1C", borderRadius: 14, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", paddingHorizontal: 14, paddingVertical: 11 },
  searchInput: { flex: 1, color: "#fff", fontSize: 15 },
  resultRow: { flexDirection: "row", alignItems: "center", paddingHorizontal: 16, paddingVertical: 10, gap: 12, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.04)" },
  resultArt: { width: 46, height: 46, borderRadius: 8 },
  resultArtFallback: { backgroundColor: "rgba(255,255,255,0.06)", alignItems: "center", justifyContent: "center" },
  resultTrack: { fontSize: 14, fontWeight: "600", color: "#fff" },
  resultArtist: { fontSize: 12, color: "rgba(255,255,255,0.45)", marginTop: 2 },
  emptyText: { textAlign: "center", color: "rgba(255,255,255,0.25)", fontSize: 14, marginTop: 32 },
  avatarSection: { alignItems: "center", paddingVertical: 24 },
  avatarWrap: { position: "relative", width: 94, height: 94 },
  avatarCircle: { width: 90, height: 90, borderRadius: 20, backgroundColor: "#FF6B35", alignItems: "center", justifyContent: "center", overflow: "hidden" },
  avatarLoading: { backgroundColor: "rgba(255,255,255,0.1)" },
  avatarInitials: { fontSize: 30, fontWeight: "800", color: "#fff" },
  avatarEditBadge: { position: "absolute", bottom: -4, right: -4, width: 26, height: 26, borderRadius: 13, backgroundColor: "#FF6C1A", borderWidth: 2, borderColor: "#111113", alignItems: "center", justifyContent: "center" },
  avatarHint: { marginTop: 10, fontSize: 12, color: "rgba(255,255,255,0.3)" },
  section: { paddingHorizontal: 20, marginBottom: 22 },
  sectionLabel: { fontSize: 11, fontWeight: "700", letterSpacing: 1, color: "rgba(255,255,255,0.3)", marginBottom: 8 },
  input: { backgroundColor: "#1A1A1C", borderRadius: 14, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", color: "#fff", fontSize: 15, paddingHorizontal: 16, paddingVertical: 13 },
  inputMulti: { minHeight: 80, paddingTop: 13, textAlignVertical: "top" },
  songRow: { flexDirection: "row", alignItems: "center", backgroundColor: "#1A1A1C", borderRadius: 14, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", padding: 12, gap: 12 },
  songArt: { width: 44, height: 44, borderRadius: 8 },
  songArtFallback: { backgroundColor: "rgba(255,255,255,0.06)", alignItems: "center", justifyContent: "center" },
  songName: { fontSize: 14, fontWeight: "600", color: "#fff" },
  songArtist: { fontSize: 12, color: "rgba(255,255,255,0.45)", marginTop: 2 },
  songPlaceholder: { fontSize: 14, color: "rgba(255,255,255,0.3)" },
  clearBtn: { marginTop: 8, alignSelf: "flex-start" },
  clearBtnText: { fontSize: 13, color: "rgba(255,100,80,0.7)" },
  linkRow: { flexDirection: "row", alignItems: "center", backgroundColor: "#1A1A1C", borderRadius: 12, borderWidth: 1, borderColor: "rgba(255,255,255,0.08)", paddingHorizontal: 14, paddingVertical: 11, marginBottom: 8, gap: 8 },
  linkText: { flex: 1, fontSize: 13, color: "rgba(255,255,255,0.65)" },
  linkInputRow: { flexDirection: "row", gap: 10, marginTop: 4 },
  linkInput: { flex: 1, backgroundColor: "#1A1A1C", borderRadius: 12, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", color: "#fff", fontSize: 14, paddingHorizontal: 14, paddingVertical: 11 },
  addLinkBtn: { width: 42, height: 42, borderRadius: 12, backgroundColor: "#FF6C1A", alignItems: "center", justifyContent: "center" },
  socialRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 10 },
  socialIconWrap: { width: 40, height: 40, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  socialInput: { flex: 1, backgroundColor: "#1A1A1C", borderRadius: 12, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", color: "#fff", fontSize: 13, paddingHorizontal: 12, paddingVertical: 10 },
  bannerPreview: { height: 150, borderRadius: 14, overflow: "hidden", backgroundColor: "#1A1A1C", alignItems: "flex-end", justifyContent: "flex-end", padding: 10 },
  bannerEditBtn: { flexDirection: "row", alignItems: "center", gap: 5, backgroundColor: "rgba(0,0,0,0.52)", borderRadius: 10, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1, borderColor: "rgba(255,255,255,0.2)" },
  bannerEditText: { fontSize: 12, fontWeight: "700" as const, color: "#fff" },
  inputLocked: { opacity: 0.4 },
  cooldownBadge: { fontSize: 11, fontWeight: "600" as const, color: "#FF6C1A", letterSpacing: 0 },
  cooldownBadgeLocked: { fontSize: 11, fontWeight: "600" as const, color: "rgba(255,100,80,0.75)", letterSpacing: 0 },
});
