import { StyleSheet, Platform, Dimensions } from "react-native";
import { SW, SH, NAVBAR_H, BOTTOM_INSET, COMPOSER_ABOVE_NAV, COLLAGE_W, COLLAGE_GAP } from "../../../lib/feed/dimensions";
import { STREAM_CARD_GAP, STREAM_CARD_W, WAVE_HEIGHTS, CARD_AVATAR_SIZE, CARD_AVATAR_OVERLAP, CARD_BANNER_H, MSG_HEADER_H, TOGGLE_W, TOGGLE_H, THUMB_SIZE, THUMB_TRAVEL, PROFILE_BANNER_H, PROFILE_AVATAR_SIZE, PROFILE_AVATAR_OVERLAP, SWATCH_SIZE } from "../../../constants/feedLayout";

// Component-scoped StyleSheets extracted from app/feed.tsx.

/** Used by components/profile/SettingsOverlay.tsx. */
export const settingsOverlayStyles = StyleSheet.create({
  sheet: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#1a1a1f",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    paddingBottom: 40,
    overflow: "hidden",
  },
  handle: {
    alignSelf: "center",
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.18)",
    marginTop: 12,
    marginBottom: 20,
  },
  title: {
    fontSize: 17,
    fontWeight: "700",
    color: "#fff",
    paddingHorizontal: 20,
    marginBottom: 8,
  },
  logoutRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 14,
    marginHorizontal: 12,
    marginTop: 4,
    backgroundColor: "rgba(255,77,109,0.08)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,77,109,0.18)",
  },
  logoutIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(255,77,109,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  logoutLabel: { flex: 1, fontSize: 15, fontWeight: "600", color: "#ff4d6d" },
  confirmBlock: { paddingHorizontal: 20, paddingTop: 8, gap: 10 },
  confirmTitle: { fontSize: 19, fontWeight: "800", color: "#fff", letterSpacing: -0.3 },
  confirmSub: { fontSize: 13, color: "rgba(255,255,255,0.45)", lineHeight: 18, marginBottom: 4 },
  saveBtn: {
    backgroundColor: "#AB00FF",
    borderRadius: 16,
    paddingVertical: 15,
    alignItems: "center",
  },
  saveBtnText: { fontSize: 15, fontWeight: "700", color: "#fff" },
  skipBtn: {
    borderRadius: 16,
    paddingVertical: 13,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  skipBtnText: { fontSize: 15, fontWeight: "600", color: "rgba(255,255,255,0.55)" },

  // â”€â”€ Generic menu row (used for Connected Apps, etc.) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  menuRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 14,
    marginHorizontal: 12,
    marginTop: 4,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  menuIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  menuLabel: { flex: 1, fontSize: 15, fontWeight: "600", color: "#fff" },

  // â”€â”€ Connected Apps sub-screen â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  subHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.07)",
    marginBottom: 8,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  subTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
  },

  // Spotify app row
  appRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginHorizontal: 16,
    marginVertical: 6,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  spotifyLogoWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "rgba(29,185,84,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  appName:   { fontSize: 15, fontWeight: "700", color: "#fff" },
  appStatus: { fontSize: 12, color: "rgba(255,255,255,0.4)", marginTop: 2 },

  // Right side of app row when connected
  connectedRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  connectedDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#1DB954",
  },
  disconnectBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },

  // Connect button (when disconnected)
  connectBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#1DB954",
  },
  connectBtnText: { fontSize: 13, fontWeight: "700", color: "#fff" },

  // Disconnect confirmation block
  disconnectConfirm: {
    marginHorizontal: 16,
    marginTop: 12,
    padding: 16,
    backgroundColor: "rgba(255,77,109,0.08)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,77,109,0.18)",
    gap: 10,
  },
  disconnectConfirmTitle: { fontSize: 15, fontWeight: "700", color: "#fff" },
  disconnectConfirmSub:   { fontSize: 13, color: "rgba(255,255,255,0.45)", lineHeight: 18 },
  disconnectBtnRow:       { flexDirection: "row", gap: 10, marginTop: 2 },
  disconnectCancelBtn: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  disconnectCancelText: { fontSize: 14, fontWeight: "600", color: "rgba(255,255,255,0.55)" },
  disconnectConfirmBtn: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#ff4d6d",
  },
  disconnectConfirmText: { fontSize: 14, fontWeight: "700", color: "#fff" },

  // â”€â”€ Preferences sub-screen â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  prefRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 14,
    marginHorizontal: 12,
    marginTop: 4,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  prefIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(171,0,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  prefLabel: { flex: 1, fontSize: 15, fontWeight: "600", color: "#fff" },
  prefSub:   { fontSize: 12, color: "rgba(255,255,255,0.4)", marginTop: 2 },
});
