import { StyleSheet, Platform, Dimensions } from "react-native";
import { SW, SH, NAVBAR_H, BOTTOM_INSET, COMPOSER_ABOVE_NAV, COLLAGE_W, COLLAGE_GAP } from "../../../../lib/feed/dimensions";
import { STREAM_CARD_GAP, STREAM_CARD_W, WAVE_HEIGHTS, CARD_AVATAR_SIZE, CARD_AVATAR_OVERLAP, CARD_BANNER_H, MSG_HEADER_H, TOGGLE_W, TOGGLE_H, THUMB_SIZE, THUMB_TRAVEL, PROFILE_BANNER_H, PROFILE_AVATAR_SIZE, PROFILE_AVATAR_OVERLAP, SWATCH_SIZE } from "../../../../constants/feedLayout";

// Component-scoped StyleSheets extracted from app/feed.tsx.


export const linksSheetStyles = StyleSheet.create({
  sheet: {
    position: "absolute", bottom: 0, left: 0, right: 0,
    backgroundColor: "#1A1A1C",
    borderTopLeftRadius: 24, borderTopRightRadius: 24,
    paddingBottom: BOTTOM_INSET + 16,
    borderTopWidth: 1, borderColor: "rgba(255,255,255,0.08)",
  },
  handle:  { width: 36, height: 4, borderRadius: 2, backgroundColor: "rgba(255,255,255,0.15)", alignSelf: "center", marginTop: 10, marginBottom: 4 },
  heading: { fontSize: 11, fontWeight: "700", letterSpacing: 1, color: "rgba(255,255,255,0.3)", textTransform: "uppercase", paddingHorizontal: 20, paddingTop: 8, paddingBottom: 10 },
  row:     { flexDirection: "row", alignItems: "center", paddingHorizontal: 20, paddingVertical: 13, gap: 12, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "rgba(255,255,255,0.07)" },
  iconWrap:    { width: 44, height: 44, borderRadius: 10, backgroundColor: "rgba(255,108,26,0.13)", alignItems: "center", justifyContent: "center" },
  spotifyWrap: { width: 44, height: 44, borderRadius: 10, backgroundColor: "rgba(29,185,84,0.12)", alignItems: "center", justifyContent: "center" },
  art:         { width: 44, height: 44, borderRadius: 8 },
  artCircle:   { width: 44, height: 44, borderRadius: 22 },
  domain: { fontSize: 14, fontWeight: "600", color: "#fff" },
  path:   { fontSize: 12, color: "rgba(255,255,255,0.35)", marginTop: 1 },
});


export const settingsOverlayStyles = StyleSheet.create({
  sheet: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#1a1a1f",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    paddingBottom: 40,
    overflow: "hidden",
  },
  handle: {
    alignSelf: "center",
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.18)",
    marginTop: 12,
    marginBottom: 20,
  },
  title: {
    fontSize: 17,
    fontWeight: "700",
    color: "#fff",
    paddingHorizontal: 20,
    marginBottom: 8,
  },
  logoutRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 14,
    marginHorizontal: 12,
    marginTop: 4,
    backgroundColor: "rgba(255,77,109,0.08)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,77,109,0.18)",
  },
  logoutIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(255,77,109,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  logoutLabel: { flex: 1, fontSize: 15, fontWeight: "600", color: "#ff4d6d" },
  confirmBlock: { paddingHorizontal: 20, paddingTop: 8, gap: 10 },
  confirmTitle: { fontSize: 19, fontWeight: "800", color: "#fff", letterSpacing: -0.3 },
  confirmSub: { fontSize: 13, color: "rgba(255,255,255,0.45)", lineHeight: 18, marginBottom: 4 },
  saveBtn: {
    backgroundColor: "#AB00FF",
    borderRadius: 16,
    paddingVertical: 15,
    alignItems: "center",
  },
  saveBtnText: { fontSize: 15, fontWeight: "700", color: "#fff" },
  skipBtn: {
    borderRadius: 16,
    paddingVertical: 13,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  skipBtnText: { fontSize: 15, fontWeight: "600", color: "rgba(255,255,255,0.55)" },

  // ── Generic menu row (used for Connected Apps, etc.) ──────────────────────
  menuRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 14,
    marginHorizontal: 12,
    marginTop: 4,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  menuIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  menuLabel: { flex: 1, fontSize: 15, fontWeight: "600", color: "#fff" },

  // ── Connected Apps sub-screen ─────────────────────────────────────────────
  subHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.07)",
    marginBottom: 8,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  subTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
  },

  // Spotify app row
  appRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginHorizontal: 16,
    marginVertical: 6,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  spotifyLogoWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "rgba(29,185,84,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  appName:   { fontSize: 15, fontWeight: "700", color: "#fff" },
  appStatus: { fontSize: 12, color: "rgba(255,255,255,0.4)", marginTop: 2 },

  // Right side of app row when connected
  connectedRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  connectedDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#1DB954",
  },
  disconnectBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },

  // Connect button (when disconnected)
  connectBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#1DB954",
  },
  connectBtnText: { fontSize: 13, fontWeight: "700", color: "#fff" },

  // Disconnect confirmation block
  disconnectConfirm: {
    marginHorizontal: 16,
    marginTop: 12,
    padding: 16,
    backgroundColor: "rgba(255,77,109,0.08)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,77,109,0.18)",
    gap: 10,
  },
  disconnectConfirmTitle: { fontSize: 15, fontWeight: "700", color: "#fff" },
  disconnectConfirmSub:   { fontSize: 13, color: "rgba(255,255,255,0.45)", lineHeight: 18 },
  disconnectBtnRow:       { flexDirection: "row", gap: 10, marginTop: 2 },
  disconnectCancelBtn: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  disconnectCancelText: { fontSize: 14, fontWeight: "600", color: "rgba(255,255,255,0.55)" },
  disconnectConfirmBtn: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#ff4d6d",
  },
  disconnectConfirmText: { fontSize: 14, fontWeight: "700", color: "#fff" },

  // ── Preferences sub-screen ────────────────────────────────────────────────
  prefRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 14,
    marginHorizontal: 12,
    marginTop: 4,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  prefIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(171,0,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  prefLabel: { flex: 1, fontSize: 15, fontWeight: "600", color: "#fff" },
  prefSub:   { fontSize: 12, color: "rgba(255,255,255,0.4)", marginTop: 2 },
});


export const profileStyles = StyleSheet.create({
  scrollContent: { padding: 10, paddingBottom: NAVBAR_H + BOTTOM_INSET + 32 },

  // Top bar — flat, no border radius
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  topBarTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#ffffff",
    letterSpacing: -0.3,
  },
  topBarRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  topBarIconBtn: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
  },
  topBarIcon: { fontSize: 18, color: "rgba(255,255,255,0.6)" },
  proBadge: {
    paddingHorizontal: 12,
    height: 30,
    borderRadius: 8,
    backgroundColor: "#AB00FF",
    alignItems: "center",
    justifyContent: "center",
  },
  proBadgeText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#fff",
    letterSpacing: 1.2,
  },
  card: { backgroundColor: "#161618", borderRadius: 24, overflow: "hidden", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  bannerWrap: { height: PROFILE_BANNER_H, overflow: "hidden" },
  bannerGlow: { position: "absolute", width: 280, height: 280, borderRadius: 140, backgroundColor: "#FF7030", opacity: 0.38, alignSelf: "center", top: -100 },
  bannerActions: { position: "absolute", bottom: 14, right: 16, flexDirection: "row", alignItems: "center", gap: 8 },
  socialBtn: { width: 34, height: 34, borderRadius: 17, backgroundColor: "rgba(0,0,0,0.35)", borderWidth: 1, borderColor: "rgba(255,255,255,0.18)", alignItems: "center", justifyContent: "center" },
  socialIcon: { fontSize: 15, color: "#fff" },
  followBtn: { paddingHorizontal: 18, height: 34, borderRadius: 17, backgroundColor: "#ffffff", alignItems: "center", justifyContent: "center" },
  followBtnText: { fontSize: 14, fontWeight: "700", color: "#111" },
  editProfileBtn: { paddingHorizontal: 16, height: 34, borderRadius: 17, backgroundColor: "rgba(255,255,255,0.12)", borderWidth: 1, borderColor: "rgba(255,255,255,0.22)", alignItems: "center", justifyContent: "center" },
  editProfileBtnText: { fontSize: 14, fontWeight: "700", color: "#fff" },
  avatarRow: { paddingHorizontal: 18, paddingBottom: 12 },
  avatar: { width: PROFILE_AVATAR_SIZE, height: PROFILE_AVATAR_SIZE, borderRadius: 18, backgroundColor: "#FF6B35", borderWidth: 3, borderColor: "#161618", alignItems: "center", justifyContent: "center" },
  avatarInitials: { fontSize: 28, fontWeight: "800", color: "#fff" },
  infoSection: { paddingHorizontal: 20, paddingBottom: 26 },
  nameRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 3 },
  name: { fontSize: 21, fontWeight: "800", color: "#ffffff" },
  verifiedBadge: { width: 20, height: 20, borderRadius: 10, backgroundColor: "#1D9BF0", alignItems: "center", justifyContent: "center" },
  verifiedText: { fontSize: 10, fontWeight: "900", color: "#fff" },
  handle: { fontSize: 14, color: "rgba(255,255,255,0.4)", marginBottom: 14 },
  bio: { fontSize: 14, color: "rgba(255,255,255,0.8)", lineHeight: 22, marginBottom: 16 },
  mention: { color: "#1D9BF0" },
  statsRow: { flexDirection: "row", alignItems: "baseline", marginBottom: 16 },
  statNum: { fontSize: 15, fontWeight: "800", color: "#ffffff" },
  statLabel: { fontSize: 14, color: "rgba(255,255,255,0.38)" },
  metaRow: { flexDirection: "row", gap: 20, flexWrap: "wrap" },
  metaItem: { flexDirection: "row", alignItems: "center", gap: 5, flex: 1, maxWidth: "55%" },
  metaIcon: { fontSize: 13, color: "rgba(255,255,255,0.28)" },
  metaText: { fontSize: 13, color: "rgba(255,255,255,0.32)" },
  linkBadge: { backgroundColor: "rgba(255,108,26,0.18)", borderRadius: 8, paddingHorizontal: 5, paddingVertical: 1 },
  linkBadgeText: { fontSize: 10, fontWeight: "800", color: "#FF6C1A" },

  // Spotify reconnect
  reconnectCard: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(29,185,84,0.08)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(29,185,84,0.2)",
    padding: 14,
  },
  reconnectTitle: { fontSize: 14, fontWeight: "700", color: "#fff" },
  reconnectSub: { fontSize: 12, color: "rgba(255,255,255,0.4)", marginTop: 2 },

  // Now Playing card
  nowPlayingCard: {
    marginTop: 12,
    borderRadius: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    padding: 16,
    gap: 14,
  },
  nowPlayingCardMeet: { borderColor: "rgba(171,0,255,0.45)" },
  npMeetBadge: {
    flexDirection: "row", alignItems: "center", gap: 7,
    alignSelf: "flex-start",
    backgroundColor: "rgba(171,0,255,0.22)",
    borderRadius: 999, paddingVertical: 6, paddingHorizontal: 12,
    marginBottom: 2,
  },
  npMeetBadgeText: { fontSize: 12, fontWeight: "700", color: "#E7CBFF", flexShrink: 1 },
  npMeetBadgeHost: { fontWeight: "800", color: "#fff" },
  npTopRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  npArt: {
    width: 68,
    height: 68,
    borderRadius: 10,
    backgroundColor: "#2a1a10",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  npArtFallback: { backgroundColor: "#2a1a10", alignItems: "center", justifyContent: "center" },
  npArtEmoji: { fontSize: 26, opacity: 0.5 },
  npInfo: { flex: 1, gap: 3 },
  npTitle: { fontSize: 15, fontWeight: "700", color: "#ffffff" },
  npArtist: { fontSize: 13, color: "rgba(255,255,255,0.45)", marginBottom: 10 },
  npProgressTrack: { height: 1, backgroundColor: "rgba(255,255,255,0.15)", borderRadius: 2, marginBottom: 5 },
  npProgressFill: { width: "35%", height: 3, backgroundColor: "#ffffff", borderRadius: 2, position: "relative" },
  npProgressThumb: { position: "absolute", right: -5, top: -4, width: 11, height: 11, borderRadius: 6, backgroundColor: "#fff" },
  npTimestamps: { flexDirection: "row", justifyContent: "space-between" },
  npTime: { fontSize: 11, color: "rgba(255,255,255,0.35)" },

  // Section tabs
  tabsWrap: { marginTop: 10 },
  tabRow: {
    flexDirection: "row",
    position: "relative",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.07)",
  },
  tabIndicator: {
    position: "absolute",
    bottom: 0,
    height: 2,
    borderRadius: 1,
    overflow: "hidden",
  },
  tabBtn: {
    paddingVertical: 12,
    alignItems: "center",
  },
  tabLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "rgba(255,255,255,0.32)",
    letterSpacing: 0.2,
  },
  tabLabelActive: {
    color: "#ffffff",
  },
  // Repost label
  repostLabel: { paddingHorizontal: 12, paddingBottom: 6, paddingTop: 2 },
  repostLabelText: { fontSize: 12, color: "rgba(255,255,255,0.35)", fontWeight: "600" },

  // Playlist list items
  playlistListItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderRadius: 14,
  },
  playlistListArt: {
    width: 56,
    height: 56,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
  },
  playlistListArtInner: { ...StyleSheet.absoluteFillObject, flexDirection: "row", flexWrap: "wrap" },
  playlistListMiniCell: { width: "50%", height: "100%" },
  playlistListName: { fontSize: 15, fontWeight: "700", color: "#fff", marginBottom: 3 },
  playlistListMeta: { fontSize: 13, color: "rgba(255,255,255,0.38)" },
  playlistChevron: { fontSize: 20, color: "rgba(255,255,255,0.25)", paddingRight: 4 },

  // Community cards
  communityCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
  },
  communityIcon: {
    width: 46,
    height: 46,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  communityName: { fontSize: 14, fontWeight: "700", color: "#fff", marginBottom: 3 },
  communityDesc: { fontSize: 12, color: "rgba(255,255,255,0.4)" },
  communityMembers: { fontSize: 13, fontWeight: "700", flexShrink: 0 },

  // Gradient toggle
  toggleTrack: {
    width: TOGGLE_W,
    height: TOGGLE_H,
    borderRadius: TOGGLE_H / 2,
    overflow: "hidden",
    justifyContent: "center",
    paddingLeft: 3,
  },
  toggleThumb: {
    width: THUMB_SIZE,
    height: THUMB_SIZE,
    borderRadius: THUMB_SIZE / 2,
    backgroundColor: "#ffffff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 3,
  },

  // Broadcast row
  broadcastRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  broadcastLabel: {
    fontSize: 14,
    color: "rgba(255,255,255,0.6)",
    fontWeight: "500",
  },

  // Start Meet button — lives inside the Now Playing card
  startMeetBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    marginTop: 12,
    paddingVertical: 11,
    borderRadius: 18,
    backgroundColor: "rgba(0,0,0,0.28)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
  },
  startMeetBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#fff",
    letterSpacing: 0.2,
  },

  // Sticky compose FAB + its option menu
  fab: {
    position: "absolute",
    right: 18,
    bottom: NAVBAR_H + BOTTOM_INSET + 14,
    width: 58, height: 58, borderRadius: 29,
    backgroundColor: "#FF6C1A",
    alignItems: "center", justifyContent: "center",
    shadowColor: "#FF6C1A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.45,
    shadowRadius: 12,
    elevation: 8,
  },
  fabMenuOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
    alignItems: "flex-end",
    paddingRight: 18,
    paddingBottom: NAVBAR_H + BOTTOM_INSET + 82,
  },
  fabMenu: {
    width: 270,
    backgroundColor: "#1A1A1C",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingVertical: 6,
    overflow: "hidden",
  },
  fabMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  fabMenuIcon: {
    width: 40, height: 40, borderRadius: 12,
    backgroundColor: "rgba(255,108,26,0.12)",
    alignItems: "center", justifyContent: "center",
  },
  fabMenuTitle: { fontSize: 15, fontWeight: "700", color: "#fff" },
  fabMenuSub: { fontSize: 12, color: "rgba(255,255,255,0.45)", marginTop: 2 },
  fabMenuDivider: { height: 1, backgroundColor: "rgba(255,255,255,0.07)", marginHorizontal: 16 },
});


export const psStyles = StyleSheet.create({
  sheet: { position: "absolute", bottom: 0, left: 0, right: 0, height: "88%", backgroundColor: "#111113", borderTopLeftRadius: 28, borderTopRightRadius: 28, overflow: "hidden", borderTopWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  navBtn: { width: 32, alignItems: "center" },
  homeContent: { paddingHorizontal: 20, paddingTop: 22, paddingBottom: 40 },
  sectionLabel: { fontSize: 11, fontWeight: "700" as const, color: "rgba(255,255,255,0.3)", letterSpacing: 1, marginBottom: 14 },
  nowPlayingCard: { flexDirection: "row" as const, alignItems: "center" as const, gap: 12, backgroundColor: "rgba(29,185,84,0.08)", borderRadius: 16, borderWidth: 1, borderColor: "rgba(29,185,84,0.2)", padding: 14 },
  npArt: { width: 52, height: 52, borderRadius: 10, flexShrink: 0 },
  npArtFallback: { backgroundColor: "rgba(255,255,255,0.06)", alignItems: "center" as const, justifyContent: "center" as const },
  npTrack: { fontSize: 14, fontWeight: "700" as const, color: "#fff" },
  npArtist: { fontSize: 12, color: "rgba(255,255,255,0.5)", marginTop: 2 },
  pinBtn: { flexDirection: "row" as const, alignItems: "center" as const, gap: 5, backgroundColor: "#1DB954", borderRadius: 10, paddingHorizontal: 12, paddingVertical: 7 },
  pinBtnText: { fontSize: 12, fontWeight: "700" as const, color: "#000" },
  addSongBtn: { flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "center" as const, gap: 10, backgroundColor: "#FF6C1A", borderRadius: 14, paddingVertical: 14 },
  addSongText: { fontSize: 15, fontWeight: "700" as const, color: "#fff" },
  divider: { height: 1, backgroundColor: "rgba(255,255,255,0.07)", marginVertical: 24 },
  menuRow: { flexDirection: "row" as const, alignItems: "center" as const, gap: 14, paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.05)" },
  menuIcon: { width: 40, height: 40, borderRadius: 12, alignItems: "center" as const, justifyContent: "center" as const },
  menuLabel: { flex: 1, fontSize: 15, fontWeight: "600" as const, color: "#fff" },
  plArt: { width: 48, height: 48, borderRadius: 8, flexShrink: 0 },
  likedArt: { backgroundColor: "rgba(29,185,84,0.1)", alignItems: "center" as const, justifyContent: "center" as const },
  plArtFallback: { backgroundColor: "rgba(255,255,255,0.06)", alignItems: "center" as const, justifyContent: "center" as const },
  // Preview step
  previewWrap: { flex: 1, alignItems: "center" as const, paddingHorizontal: 28, paddingTop: 20, paddingBottom: 28 },
  previewArt: { width: 190, height: 190, borderRadius: 18, marginBottom: 22 },
  previewArtFallback: { backgroundColor: "rgba(255,255,255,0.06)", alignItems: "center" as const, justifyContent: "center" as const },
  previewTrack: { fontSize: 20, fontWeight: "800" as const, color: "#fff", textAlign: "center" as const, marginBottom: 6 },
  previewArtist: { fontSize: 14, color: "rgba(255,255,255,0.45)", textAlign: "center" as const, marginBottom: 24 },
  previewProgressTrack: { width: "100%", height: 4, backgroundColor: "rgba(255,255,255,0.12)", borderRadius: 2, marginBottom: 8 },
  previewProgressFill: { height: 4, backgroundColor: "#1DB954", borderRadius: 2 },
  previewTimes: { width: "100%", flexDirection: "row" as const, justifyContent: "space-between" as const, marginBottom: 20 },
  previewTime: { fontSize: 11, color: "rgba(255,255,255,0.35)", fontWeight: "600" as const },
  noPreviewText: { fontSize: 13, color: "rgba(255,255,255,0.3)", marginVertical: 24, fontStyle: "italic" as const },
  playPauseBtn: { width: 60, height: 60, borderRadius: 30, backgroundColor: "#1DB954", alignItems: "center" as const, justifyContent: "center" as const, marginBottom: 28 },
  previewActions: { flexDirection: "row" as const, gap: 12, width: "100%", marginBottom: 14 },
  openBtn: { flex: 1, flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "center" as const, gap: 7, height: 46, borderRadius: 14, backgroundColor: "rgba(29,185,84,0.12)", borderWidth: 1, borderColor: "rgba(29,185,84,0.3)" },
  openBtnText: { fontSize: 14, fontWeight: "700" as const, color: "#1DB954" },
  saveBtn: { flex: 1, flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "center" as const, gap: 7, height: 46, borderRadius: 14, backgroundColor: "rgba(255,255,255,0.07)", borderWidth: 1, borderColor: "rgba(255,255,255,0.14)" },
  saveBtnSaved: { backgroundColor: "rgba(29,185,84,0.1)", borderColor: "rgba(29,185,84,0.28)" },
  saveBtnText: { fontSize: 14, fontWeight: "600" as const, color: "rgba(255,255,255,0.7)" },
  saveBtnTextSaved: { color: "#1DB954" },
  pinCTA: { flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "center" as const, gap: 8, width: "100%", height: 52, borderRadius: 16, backgroundColor: "#FF6C1A" },
  pinCTAText: { fontSize: 16, fontWeight: "800" as const, color: "#000" },
});


export const epOverlayStyles = StyleSheet.create({
  backdrop: { backgroundColor: "rgba(0,0,0,0.70)" },
  sheet: {
    position: "absolute", bottom: 0, left: 0, right: 0, height: "92%",
    backgroundColor: "#111113",
    borderTopLeftRadius: 28, borderTopRightRadius: 28,
    overflow: "hidden",
    borderTopWidth: 1, borderColor: "rgba(255,255,255,0.08)",
  },
  songSheet: {
    position: "absolute", bottom: 0, left: 0, right: 0, height: "75%",
    backgroundColor: "#111113",
    borderTopLeftRadius: 24, borderTopRightRadius: 24,
    overflow: "hidden",
    borderTopWidth: 1, borderColor: "rgba(255,255,255,0.08)",
    paddingBottom: 20,
  },
  handle: { width: 36, height: 4, borderRadius: 2, backgroundColor: "rgba(255,255,255,0.15)", alignSelf: "center", marginTop: 10, marginBottom: 4 },
  sheetHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 20, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.07)" },
  sheetTitle: { fontSize: 16, fontWeight: "700", color: "#fff" },
  closeBtn: { fontSize: 16, color: "rgba(255,255,255,0.45)", fontWeight: "600" },
  cancelBtn: { fontSize: 15, color: "rgba(255,255,255,0.5)" },
  saveBtn: { fontSize: 15, fontWeight: "700", color: "#FF6C1A" },
  searchRow: { flexDirection: "row", alignItems: "center", margin: 16, backgroundColor: "#1A1A1C", borderRadius: 14, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", paddingHorizontal: 14, paddingVertical: 11 },
  searchInput: { flex: 1, color: "#fff", fontSize: 15 },
  resultRow: { flexDirection: "row", alignItems: "center", paddingHorizontal: 16, paddingVertical: 10, gap: 12, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.04)" },
  resultArt: { width: 46, height: 46, borderRadius: 8 },
  resultArtFallback: { backgroundColor: "rgba(255,255,255,0.06)", alignItems: "center", justifyContent: "center" },
  resultTrack: { fontSize: 14, fontWeight: "600", color: "#fff" },
  resultArtist: { fontSize: 12, color: "rgba(255,255,255,0.45)", marginTop: 2 },
  emptyText: { textAlign: "center", color: "rgba(255,255,255,0.25)", fontSize: 14, marginTop: 32 },
  avatarSection: { alignItems: "center", paddingVertical: 24 },
  avatarWrap: { position: "relative", width: 94, height: 94 },
  avatarCircle: { width: 90, height: 90, borderRadius: 20, backgroundColor: "#FF6B35", alignItems: "center", justifyContent: "center", overflow: "hidden" },
  avatarLoading: { backgroundColor: "rgba(255,255,255,0.1)" },
  avatarInitials: { fontSize: 30, fontWeight: "800", color: "#fff" },
  avatarEditBadge: { position: "absolute", bottom: -4, right: -4, width: 26, height: 26, borderRadius: 13, backgroundColor: "#FF6C1A", borderWidth: 2, borderColor: "#111113", alignItems: "center", justifyContent: "center" },
  avatarHint: { marginTop: 10, fontSize: 12, color: "rgba(255,255,255,0.3)" },
  section: { paddingHorizontal: 20, marginBottom: 22 },
  sectionLabel: { fontSize: 11, fontWeight: "700", letterSpacing: 1, color: "rgba(255,255,255,0.3)", marginBottom: 8 },
  input: { backgroundColor: "#1A1A1C", borderRadius: 14, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", color: "#fff", fontSize: 15, paddingHorizontal: 16, paddingVertical: 13 },
  inputMulti: { minHeight: 80, paddingTop: 13, textAlignVertical: "top" },
  songRow: { flexDirection: "row", alignItems: "center", backgroundColor: "#1A1A1C", borderRadius: 14, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", padding: 12, gap: 12 },
  songArt: { width: 44, height: 44, borderRadius: 8 },
  songArtFallback: { backgroundColor: "rgba(255,255,255,0.06)", alignItems: "center", justifyContent: "center" },
  songName: { fontSize: 14, fontWeight: "600", color: "#fff" },
  songArtist: { fontSize: 12, color: "rgba(255,255,255,0.45)", marginTop: 2 },
  songPlaceholder: { fontSize: 14, color: "rgba(255,255,255,0.3)" },
  clearBtn: { marginTop: 8, alignSelf: "flex-start" },
  clearBtnText: { fontSize: 13, color: "rgba(255,100,80,0.7)" },
  linkRow: { flexDirection: "row", alignItems: "center", backgroundColor: "#1A1A1C", borderRadius: 12, borderWidth: 1, borderColor: "rgba(255,255,255,0.08)", paddingHorizontal: 14, paddingVertical: 11, marginBottom: 8, gap: 8 },
  linkText: { flex: 1, fontSize: 13, color: "rgba(255,255,255,0.65)" },
  linkInputRow: { flexDirection: "row", gap: 10, marginTop: 4 },
  linkInput: { flex: 1, backgroundColor: "#1A1A1C", borderRadius: 12, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", color: "#fff", fontSize: 14, paddingHorizontal: 14, paddingVertical: 11 },
  addLinkBtn: { width: 42, height: 42, borderRadius: 12, backgroundColor: "#FF6C1A", alignItems: "center", justifyContent: "center" },
  socialRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 10 },
  socialIconWrap: { width: 40, height: 40, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  socialInput: { flex: 1, backgroundColor: "#1A1A1C", borderRadius: 12, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", color: "#fff", fontSize: 13, paddingHorizontal: 12, paddingVertical: 10 },
  bannerPreview: { height: 150, borderRadius: 14, overflow: "hidden", backgroundColor: "#1A1A1C", alignItems: "flex-end", justifyContent: "flex-end", padding: 10 },
  bannerEditBtn: { flexDirection: "row", alignItems: "center", gap: 5, backgroundColor: "rgba(0,0,0,0.52)", borderRadius: 10, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1, borderColor: "rgba(255,255,255,0.2)" },
  bannerEditText: { fontSize: 12, fontWeight: "700" as const, color: "#fff" },
  inputLocked: { opacity: 0.4 },
  cooldownBadge: { fontSize: 11, fontWeight: "600" as const, color: "#FF6C1A", letterSpacing: 0 },
  cooldownBadgeLocked: { fontSize: 11, fontWeight: "600" as const, color: "rgba(255,100,80,0.75)", letterSpacing: 0 },
});


export const bcOverlayStyles = StyleSheet.create({
  backdrop: { backgroundColor: "rgba(0,0,0,0.6)" },
  sheet: { position: "absolute", bottom: 0, left: 0, right: 0, height: "75%", backgroundColor: "#1A1A1C", borderTopLeftRadius: 24, borderTopRightRadius: 24, overflow: "hidden", borderTopWidth: 1, borderColor: "rgba(255,255,255,0.1)" },
  handle: { width: 36, height: 4, borderRadius: 2, backgroundColor: "rgba(255,255,255,0.15)", alignSelf: "center", marginTop: 10, marginBottom: 4 },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 20, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.07)" },
  title: { fontSize: 16, fontWeight: "700" as const, color: "#fff" },
  closeBtn: { fontSize: 16, color: "rgba(255,255,255,0.45)", fontWeight: "600" as const },
  content: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 40 },
  imageBox: { height: 120, borderRadius: 16, borderWidth: 1.5, borderColor: "rgba(255,255,255,0.15)", borderStyle: "dashed" as const, alignItems: "center", justifyContent: "center", gap: 8, overflow: "hidden", backgroundColor: "#1A1A1C" },
  imageOverlay: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundColor: "rgba(0,0,0,0.45)", alignItems: "center", justifyContent: "center", gap: 6 },
  imageBoxText: { fontSize: 14, color: "rgba(255,255,255,0.5)", fontWeight: "600" as const },
  dividerRow: { flexDirection: "row", alignItems: "center", marginVertical: 22, gap: 12 },
  dividerLine: { flex: 1, height: 1, backgroundColor: "rgba(255,255,255,0.08)" },
  dividerText: { fontSize: 12, color: "rgba(255,255,255,0.25)", fontWeight: "600" as const },
  colorRow: { flexDirection: "row" as const, justifyContent: "space-between" as const, marginBottom: 10 },
  colorSwatch: { borderRadius: 14, alignItems: "center" as const, justifyContent: "center" as const },
  colorSwatchSelected: { borderWidth: 2.5, borderColor: "#fff" },
});


export const bsOverlayStyles = StyleSheet.create({
  sheet: { position: "absolute", bottom: 0, left: 0, right: 0, height: "78%", backgroundColor: "#1A1A1C", borderTopLeftRadius: 24, borderTopRightRadius: 24, overflow: "hidden", borderTopWidth: 1, borderColor: "rgba(255,255,255,0.1)" },
  sectionLabel: { fontSize: 11, fontWeight: "700" as const, color: "rgba(255,255,255,0.35)", letterSpacing: 1, marginBottom: 14 },
  shapeCell: { height: SWATCH_SIZE + 26, borderRadius: 14, backgroundColor: "rgba(255,255,255,0.07)", alignItems: "center" as const, justifyContent: "center" as const },
  shapeCellSelected: { backgroundColor: "rgba(255,108,26,0.18)", borderWidth: 1.5, borderColor: "#FF6C1A" },
  shapeIconWrap: { flex: 1, alignItems: "center" as const, justifyContent: "center" as const },
  shapeLabel: { fontSize: 10, color: "rgba(255,255,255,0.4)", fontWeight: "600" as const, paddingBottom: 7 },
  shapeLabelSelected: { color: "#FF6C1A" },
  disabledHint: { fontSize: 12, color: "rgba(255,255,255,0.35)", textAlign: "center" as const, marginBottom: 14, fontStyle: "italic" as const },
});
